### ISSUE TITLE
Supplier: problem with bank payments

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#101]
We have problems during performing payments to suppliers (bank payment).

E.g.: Supplier's invoice 8 (on demo).

We issued 3 times the payments (see the photo)
![image](https://user-images.githubusercontent.com/37332394/57210342-9da78300-6fdc-11e9-8b73-d010ef980456.png)

but no one of these payments is tracked in the report (note: payment are registered without flag "paid").

![image](https://user-images.githubusercontent.com/37332394/57210355-adbf6280-6fdc-11e9-9727-b03c26296904.png)

When we try to post the payment with flag "Paid", it returns the following mistake.

![image](https://user-images.githubusercontent.com/37332394/57210409-de070100-6fdc-11e9-843a-5567d9c33680.png)

![image](https://user-images.githubusercontent.com/37332394/57210440-f119d100-6fdc-11e9-87af-5c36a92b3a10.png)

In the general list, it shows that invoices are paid (note: not all are paid):
![image](https://user-images.githubusercontent.com/37332394/57210491-21fa0600-6fdd-11e9-960e-8752a2ada7b5.png)

**Comment by ValentinaKopeva** [comment]
![Безымянный](https://user-images.githubusercontent.com/38491307/58513703-c1f41b00-81a8-11e9-8a6c-7d5d1a1f138f.png)
fixed
