### ISSUE TITLE
SALES, Counterparty data - mistake when pressing on Amount OVerdue

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#103]
In counterparty, pressing on Amount OVerdue value, i get the following mistake:

![image](https://user-images.githubusercontent.com/37332394/57573334-6135b600-7426-11e9-9a72-c97a66a830b4.png)

**Comment by michelebr76** [comment]
Mistakes maybe be connected with SalesAgent.

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/57610614-d796fd00-7579-11e9-9b93-25ad49c330d4.png)
error resolved
