### ISSUE TITLE
SIMON: Not clear how to fix "Agent"

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#106]
During the import from TABLET NOBISOFT not clear how is defined agent.

During importing (see photos) a mistake is registered cause not possibile to identify the AGENT.
![image](https://user-images.githubusercontent.com/37332394/58440841-69a41700-80dd-11e9-9dfb-ab90058a648f.png)

Not clear how to is controlled the AGENT CODE.

Please note, that we asked to create a table (AGENT TABLE) where should be managed such information:
![image](https://user-images.githubusercontent.com/37332394/58440928-2dbd8180-80de-11e9-91af-7c87240a5db4.png)

The AGENT CODE should refers to the lines of this table.

**Comment by ValentinaKopeva** [comment]
Drop me the file you are trying to download.

**Comment by michelebr76** [comment]
You can try one of the follwoing file

 

 

 

 

Ing. Michele Brustia

Direttore 1C:Italia

https://www.1c-erp.it/

**Comment by ValentinaKopeva** [comment]
This is fixed
