### ISSUE TITLE
Company Data ->Fattura Elettronica -> Correction in the data

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#107]
In Company Data, tab "Fattura Elettronica", some minor corrections are required:

![image](https://user-images.githubusercontent.com/37332394/58441100-7295e800-80df-11e9-82d2-d456cb1d8b20.png)

**Field "Codice SDI"** - > Should be 7 Digits (Fixed Lenght)
**Field "Capitale Sociale"** -> Please remove the "Calculator icon"

**Comment by ValentinaKopeva** [comment]
Field "Codice SDI" - > Should be 7 Digits (Fixed Lenght) - done
_________
Field "Capitale Sociale" -> Please remove the "Calculator icon"
This is standard pictures
I can only change to another icon. Completely impossible to remove, this is the mechanism of the platform.  For example in screen
You may send me another picture and I load this in "Capitale Sociale"
![image](https://user-images.githubusercontent.com/38491307/58470149-be7d7700-8149-11e9-91c4-ef0c52789264.png)
