### ISSUE TITLE
Company Data -> Lenghts of TIN and VAT number

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#108]
In company data, TAB General Information,

![image](https://user-images.githubusercontent.com/37332394/58441240-aae9f600-80e0-11e9-9ff9-2b2ad8a3a8d9.png)

Field "VAT NUMBER" should be always 11 digits (MANDATORY) and can be just figures

Field TIN have two possibility:
- In case of "Legal Entity", lenght is 11 digits (MANDATORY) and can be just figures
- In case of "Individual", lenght is 16 digits (MANDATORY) and is alphanumeric

**Comment by ValentinaKopeva** [comment]
I sent this question to the developers of the Drive, I can not change the details created by the developers in the original version

**Comment by ValentinaKopeva** [comment]
At the moment, the length of the "VAT NUMBER" =  11 digits  and  "TIN"= 20 digits
Creating a new requisite for length sharing is not a good idea, because errors will appear in the database

**Comment by michelebr76** [comment]
Ok

Eng. Michele Brustia
Direttore 1C Italia
Via Giovanni Durando 39, Milano
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
https://www.1c-erp.it
