### ISSUE TITLE
Counterparty Data -> Change Form, not visible some data

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#109]
In the Counterpary Data, some important fields are not valorized in the part "**Legal Data**".

![image](https://user-images.githubusercontent.com/37332394/58441393-07014a00-80e2-11e9-9fb7-936e7418e1eb.png)

Required changes/Additions:
- Legal Data should be always visible (expand it)
- In case of "Legal Entity", the following fields should be visible:
a) Registration Number
b) TIN
c) VAT

- In case of "Individual", the following fields should be visible:
a) TIN
b) VAT number
c) Gender
d) Birth date

NOTE: Please check that in standard 1C:Drive they are already visible

**Comment by ValentinaKopeva** [comment]
This bug has been fixed.
