### ISSUE TITLE
Gruppo SIMON: not registering document cause missing automatic GL Account and mistake in checking stock

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#113]
The file is loaded and the product is correctly mapped and loaded, but the sales document is not posted cause missing GL Account (it seems it doesn't take the one specificed by default).

![image](https://user-images.githubusercontent.com/37332394/58535812-128e6700-81ef-11e9-8ca0-e00ac72e71a2.png)

Problem is fixed if we manually put the GL Account.
But document is not posted in any case cause it says products is missing (despite we have it in stock - see pictures).

![image](https://user-images.githubusercontent.com/37332394/58536108-e6bfb100-81ef-11e9-8c7c-47d47513437a.png)

File used to do the test attached (as ZIP cause not possibile to load other type)
[TEST.zip](https://github.com/asandulsky/1C-Italia/files/3231072/TEST.zip)

**Comment by ValentinaKopeva** [comment]
Check this
