### ISSUE TITLE
Digital Invoice, mistake in ID Paese

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#114]
Trying to generate Digital Invoice we have the following mistake:

![image](https://user-images.githubusercontent.com/37332394/58537732-c4c82d80-81f3-11e9-930b-7b7751118a32.png)

Mistake it seems connected with Country ID.
This value is at the moment fixed (cause we manage just in italy) and it is: **IT**

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/58554653-38802f80-8220-11e9-9259-fdfcd744ecb7.png)



[Desktop.zip](https://github.com/asandulsky/1C-Italia/files/3232247/Desktop.zip)
May you try again?

**Comment by michelebr76** [comment]
Fixed.

Now i will check if we need to correct some fields.

 

Ing. Michele Brustia

Direttore 1C:Italia

https://www.1c-erp.it/
