### ISSUE TITLE
Uploading from Tablet: mistake in cash receipt

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#115]
Uploading file to 1C from Tablet, there is a mistake in registering "cash receipt".
See picture.

![image](https://user-images.githubusercontent.com/37332394/58588011-fcb88a80-825e-11e9-80dc-d7c71ae796c3.png)

file used is attached in zip (the same of before)
[TEST.zip](https://github.com/asandulsky/1C-Italia/files/3234298/TEST.zip)

**Comment by ValentinaKopeva** [comment]
Error fixed
