### ISSUE TITLE
Digital Invoice -> Incorrect field regarding name of the bank

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#117]
We are doing test for digital invoice.

On the following document (in pdf and xml) we have a little mistake in the field "Istituto"
[Sample of Invoice.pdf](https://github.com/asandulsky/1C-Italia/files/3237600/Sample.of.Invoice.pdf)
[IT01620470623_00019.zip](https://github.com/asandulsky/1C-Italia/files/3237601/IT01620470623_00019.zip)

Line is the following:
<IstitutoFinanziario>IT23Y0526275340CC1310104874, in Banca Popolare Pugliese</IstitutoFinanziario>

We need to take another field from database connect with bank account
![image](https://user-images.githubusercontent.com/37332394/58643394-7738e700-82ff-11e9-9eac-65c8c37cdcf4.png)

We need to put just the name of the "BANK" (in this case "Banca Popolare Pugliese")

**Comment by ValentinaKopeva** [comment]
This task is completed.
