### ISSUE TITLE
Digital Invoice -> Import

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#119]
The import of Digital Invoice is not working.

Mistake is: "Cannot Convert Value To date".

NOTE: photo and files to test you can find in the following link (I have problem in sharing directly from Mac):

https://drive.google.com/open?id=1TtLyqkxgmOKARBnXPu5Ocj9ICZAn9HY7

**Comment by ValentinaKopeva** [comment]
Fixed
