### ISSUE TITLE
UPS: Crash when Accepting Goods from "Vendors Invoice"

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#12]
There is crash when the following operation is performed:
From vendors invoice, GENERATE-> Goods acceptance

**Comment by ValentinaKopeva** [comment]
Good afternoon, could you make a photo of the "Vendors Invoice" document, which contains an error?

**Comment by michelebr76** [comment]
I will try a bit later. This ticket is very old, and it is even possibile that it was solved with update.

Eng. Michele Brustia
Tel: +7 918 4113551
Email: michele.brustia@gmail.com

**Comment by michelebr76** [comment]
I did not reply again this crash. In any case it is a secondary problem. I close this issue. We need to concentrate on others.

**Comment by ValentinaKopeva** [comment]
Ок
