### ISSUE TITLE
Digital Invoice -> Creating Supplier Invoice

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#120]
We registered mistakes in Creating Supplier Invoice from Digital Invoice.

We do the mapping (of the supplier and of the products), but when we import (download) the invoice, products are not identified (just the one we create new are mapped)

Photos of the mistakes and file are here: 
https://drive.google.com/drive/folders/1TtLyqkxgmOKARBnXPu5Ocj9ICZAn9HY7

**Comment by ValentinaKopeva** [comment]
Check this

**Comment by michelebr76** [comment]
I noticed that an invoice as been generated, but when I try to create others, now I receive the following message:
"Value is not of Object Type"

here you can find some digital invoice to use as test:
https://drive.google.com/drive/folders/1TtLyqkxgmOKARBnXPu5Ocj9ICZAn9HY7

**Comment by ValentinaKopeva** [comment]
Check

**Comment by michelebr76** [comment]
Now it seems it is fine.

**Comment by michelebr76** [comment]
Now it seems it is fine.
