### ISSUE TITLE
Gruppo Simon -> Mistake when importing file from tablet

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#121]
When we import file from tablet we receive two mistakes that we already had and were fixed (please check why mistake we have again):

Mistake 1:
Sales invoice not posted cause missing "GL Account" (they should be automatically settled)
![image](https://user-images.githubusercontent.com/37332394/59119701-b694b280-8953-11e9-9e2a-b62f71559c86.png)

Mistake 2:
When we put the "GL Accounts" manually, we get a mistake of shortage of products
![image](https://user-images.githubusercontent.com/37332394/59119749-daf08f00-8953-11e9-8590-629c94810f90.png)

Despite we have a lot of them (see report)
![image](https://user-images.githubusercontent.com/37332394/59119790-ee035f00-8953-11e9-8cd7-12aa13a93365.png)

We have also another mistake when we create the "Warehouse transfer".
![image](https://user-images.githubusercontent.com/37332394/59119860-2efb7380-8954-11e9-8b6f-13d309de31fb.png)

Operation should be fixed like "Transfer"

[Test - Age.zip](https://github.com/asandulsky/1C-Italia/files/3266853/Test.-.Age.zip)

**Comment by ValentinaKopeva** [comment]
Mistake 1 - DONE
Mistake 2  - In process
3) Operation should be fixed like "Transfer" - DONE

**Comment by michelebr76** [comment]
Ok. Did you understand why this problem again appears

Eng. Michele Brustia
Direttore 1C Italia
Via Giovanni Durando 39, Milano
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
https://www.1c-erp.it

**Comment by ValentinaKopeva** [comment]
Mistake 2 - check

**Comment by michelebr76** [comment]
The problem is registered just when using MAC (maybe problem is the thin client used).

No problem using a PC and also no problem for the final client
