### ISSUE TITLE
Import from tablet -> INVENTORY TRANSFERS

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#122]
The interface correctly create "Inventory Transfers" but there are some problems of direction (it works fine when we put "Magazzino Principale" cause it is not actually doing any movement, just writing documents).

To solve the issue, in interface, please create 2 fields (now there is one) for warehouse:
a)  Field 1: "Main Warehouse" (In Italian: Magazzino Principale) -> It is the central warehouse
b) Field 2: "Mobile Warehouse" (In Italian: Magazzino Mobile) -> It is the warehouse of the seller (usually a VAN)

![Warehouse](https://user-images.githubusercontent.com/37332394/59326381-b1828b00-8ce6-11e9-9c3c-ae395c01936c.jpg)

After creating this fields, when importing from TABLET direction is controlled by the field 4 of lines MOBOLTES (lines controlling the header of documents) and MOBOLCOR (lines controlling the lines of documents).

We can have the following situation:
**- XE** -> in this case SKIP the line (as we understood it is automatically generated and nothing needed from us), not create any document
### - RI -> It is a ulload **FROM** "mobile warehouse" **TO** "mainwarehouse" (direction should be this)
In case the lines has other codes, we need to skip and not to create anything

In attachment (zipped) a file that can be used as test.

[AGE001.zip](https://github.com/asandulsky/1C-Italia/files/3279798/AGE001.zip)

NOTE: the file generated by costumer has two documents that are not registered (this is connected with another mistake)

To help you, here i copied the lines you can see in this file and marked the code controlling the direction

moboltes|I|001|**XE**|00000001|11/06/2019|15:29|        |11/06/2019|S|00000001|11/06/2019|15:29|A|          |11/06/2019| |   |00000002| | |              
moboltes|I|001|**XI**|00000002|11/06/2019|15:32|00000001|11/06/2019|S|00000002|11/06/2019|15:32|T|          |11/06/2019|D|   |00000001| | |              
moboltes|I|001|**XI**|00000003|11/06/2019|15:38|00000001|11/06/2019|S|00000003|11/06/2019|15:38|T|          |11/06/2019|D|   |00000001| | |              
moboltes|I|001|**RI**|00000001|11/06/2019|15:47|        |11/06/2019|S|00000001|11/06/2019|15:47|T|          |11/06/2019| |   |00000001| | |              
mobolcor|I|001|**XI**|00000002|11/06/2019|15:32|00001|01|02     |0000002|kg|00000020,000|TVE|                    |  |00000000,000|**CA**|00000000|              
mobolcor|I|001|**XI**|00000002|11/06/2019|15:32|00002|01|0530   |5300000|kg|00000010,000|TVE|                    |  |00000000,000|CA|00000000|              
mobolcor|I|001|**XI**|00000002|11/06/2019|15:32|00003|01|0100   |1000000|ct|00000010,000|TVE|                    |  |00000000,000|CA|00000000|              
mobolcor|I|001|**XI**|00000002|11/06/2019|15:32|00004|01|0352   |3520000|ct|00000020,000|TVE|                    |  |00000000,000|CA|00000000|              
mobolcor|I|001|**XI**|00000003|11/06/2019|15:38|00001|01|0216   |0000067|pz|00000010,000|TVE|                    |  |00000000,000|CA|00000000|              
mobolcor|I|001|**XI**|00000003|11/06/2019|15:38|00002|01|02     |0000002|kg|00000060,000|TVE|                    |  |00000000,000|CA|00000000|              
mobolcor|I|001|**RI**|00000001|11/06/2019|15:47|00001|01|0100   |1000000|ct|00000001,000|RA-|                    |  |00000000,000|RV|00000000|              
mobolcor|I|001|**RI**|00000001|11/06/2019|15:47|00002|01|0352   |3520000|ct|00000020,000|RA-|                    |  |00000000,000|RV|00000000|              
mobolcor|I|001|**RI**|00000001|11/06/2019|15:47|00003|01|0600   |0000194|pz|00000002,000|RA-|                    |  |00000000,000|RV|00000000|

**Comment by ValentinaKopeva** [comment]
check this

**Comment by ValentinaKopeva** [comment]
But in Table agent we have field "Warehouse" and  before when we create docunent "Inventory Transfers" in field "TO"  got a warehouse from  Table agent. 
Now you write another algorithm.

**Comment by michelebr76** [comment]
I noticed that we had a former algorytm, but we need more flexibility in phase of import. That's why we needed to change.

**Comment by michelebr76** [comment]
But despite this, . when I try to post, there again the problem: it is not posting despite there is stock.

Can you check if problem is also with you?
Maybe changing the algorithm we lost some parameters.



Problem here
![image](https://user-images.githubusercontent.com/37332394/59450210-03233680-8e09-11e9-9c66-63f147935ec3.png)

File used is this:
[AGE001.zip](https://github.com/asandulsky/1C-Italia/files/3287156/AGE001.zip)

**Comment by michelebr76** [comment]
A mistake is that now we need to change the Warehouse to consider as "Warehouse" from where download the goods. The warehouse should be: the second one "Mobile Warehouse".

**Comment by ValentinaKopeva** [comment]
Stock balance error resolved

**Comment by michelebr76** [comment]
Good! Well done!
