### ISSUE TITLE
Digital Invoice -> Minor changes in Digital Invoice (Creating)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#124]
Creating the digital Invoice, we need to change some fields.

- As "Number" field 2.1.1.4 <numero> we need to select "Number from File" field (this correction to be applied JUST for Gruppo Simon project)
- We need to delete fields related to 2.1.8 DDT (in this case we don't have any DDT document)

Hhere the part that should be changed in the XML:
-<DatiGenerali>
-<DatiGeneraliDocumento>
<TipoDocumento>TD01</TipoDocumento>
<Divisa>EUR</Divisa>
<Data>2019-06-11</Data>
<Numero>**### **TO PUT THE **NUMBER FROM FILE******</Numero>
<ImportoTotaleDocumento>715.07</ImportoTotaleDocumento>
</DatiGeneraliDocumento>
-<DatiDDT>
### **THERE IS NO DDT, NOT CONSIDER THIS PART**
</DatiDDT>
</DatiGenerali>

Here attached Digital Invoice Created but not correct.

[Digital Invoice Sample.zip](https://github.com/asandulsky/1C-Italia/files/3290900/Digital.Invoice.Sample.zip)

To check can be used document: SI00-000004

**Comment by ValentinaKopeva** [comment]
- As "Number" field 2.1.1.4  - DONE
- 2.1.8 DDT , 
field "include DDT" added to section "Addition information",  depending the selected value, you see or don't see 2.1.8 DDT 
![image](https://user-images.githubusercontent.com/38491307/59586233-1bd26b80-90eb-11e9-938e-2fdb09521175.png)

**Comment by michelebr76** [comment]
Good! I will check when I can!

Eng. Michele Brustia
Direttore 1C Italia
Via Giovanni Durando 39, Milano
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
https://www.1c-erp.it
