### ISSUE TITLE
Gruppo Simon -> Not posting sales Invoice (missing Accounts)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#125]
Again not working automatic selections of accounts for Gruppo Simon.
Impossible to post any Sales Invoice.

Mistakes in pictures:
![image](https://user-images.githubusercontent.com/37332394/59994780-6e64d800-9655-11e9-8788-497eb162c302.png)
![image](https://user-images.githubusercontent.com/37332394/59994790-77ee4000-9655-11e9-9056-83b52bf463a6.png)

I got use creating an invoice directly (not using the Tablet).

**Comment by michelebr76** [comment]
Here the correct account we should have
![image](https://user-images.githubusercontent.com/37332394/59995075-6f4a3980-9656-11e9-94bf-4fa9b5786bf4.png)

Maybe problems is connected with the fact that it was deleted the existing invoices.

**Comment by ValentinaKopeva** [comment]
check this
