### ISSUE TITLE
Gruppo Simon -> Not opening master Data of "Counterparties"

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#126]
This mistake we had already and it should be connected with updating the system (it was not request).
impossibile to open the counterparties cause we get the following mistake:

![image](https://user-images.githubusercontent.com/37332394/59995932-221b9700-9659-11e9-819d-e92a0ad5fa26.png)

![image](https://user-images.githubusercontent.com/37332394/59995979-3d86a200-9659-11e9-862c-b85588c548f2.png)

**Comment by ValentinaKopeva** [comment]
check
