### ISSUE TITLE
Mistake inserting initial balance of 1C-ERP

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#14]
There is a mistake when inserting the balance of 1C-ERP that actually it is equal to zero with the excetion of the Equity (500 Euro) registered in cash.

![image](https://user-images.githubusercontent.com/37332394/44787053-5556dc00-ab96-11e8-88f0-8d19df8e6272.png)

not sure the screen has been uploaded correctly.

**Comment by ValentinaKopeva** [comment]
Good morning, could you attach the photo with the section and the document that you are creating?

**Comment by michelebr76** [comment]
I am inserting the initial balance of the company... where actually I need just to put 500 Euros as pettycash...

![image](https://user-images.githubusercontent.com/37332394/44971970-d677ef80-af57-11e8-867f-f94677ddc87e.png)

**Comment by michelebr76** [comment]
Any news about this issue?
We need to use this system of our inner accounting and it is not working.... i cannot insert cash and register payment..

**Comment by ValentinaKopeva** [comment]
I am working on this issue

**Comment by ValentinaKopeva** [comment]
Attach a screen with all your actions, after which an error occurs

**Comment by michelebr76** [comment]
Error occurs at the end, when saving.
I attached the error opening the ticket. Can you see it?

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
Yes, I understad you.

**Comment by ValentinaKopeva** [comment]
How do you enter these settings?

**Comment by michelebr76** [comment]
I did like always:
I simply create a new "cash" and wrote 500 euros..

Did you try to do it in English? I have access just in Italian.
Maybe the problem is connected with a language mistake... 


Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
It's unlikely that the error depends on the language, the error is fixed, right?

**Comment by michelebr76** [comment]
I don't understand. Did you check and fixed ?

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
![1](https://user-images.githubusercontent.com/38491307/45093667-c3b11680-b121-11e8-89ef-a29692a9481f.png)
How do you go into these settings?
