### ISSUE TITLE
Standard Lists

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#15]
We need to create some standard lists that should be automatically loaded to any new implementation of drive. I create such list in DEMO and using it, we need to move to all others.

The first standard lists to create are the following catalogs:
- Legal Forms
- VAT rate

**Comment by ValentinaKopeva** [comment]
![2](https://user-images.githubusercontent.com/38491307/49223950-3bc16c80-f3f1-11e8-9c4d-99d57fbf7574.PNG)
![1](https://user-images.githubusercontent.com/38491307/49223952-3bc16c80-f3f1-11e8-829f-ab65b1509c1b.PNG)
Done.
Close this question
