### ISSUE TITLE
Interface with Costumer Agent System

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#16]
The Costumer decided to use his own Agent System. It is requested to create an interface to load data.
Technical information about the Agent System we already got

**Comment by michelebr76** [comment]
Here the track from NOBISOFT.

[Tracciati_TvCe_Android_6.095.pdf](https://github.com/asandulsky/1C-Italia/files/2621925/Tracciati_TvCe_Android_6.095.pdf)

Interface should works not online but allow to load files.

**Comment by asandulsky** [comment]
[icsvmexalimpgrupposimon.zip](https://github.com/asandulsky/1C-Italia/files/2628973/icsvmexalimpgrupposimon.zip)

**Comment by michelebr76** [comment]
What is this ?

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
Any action from my side on it?

As I understood it is the data we received from Simone…

**Comment by ValentinaKopeva** [comment]
![0](https://user-images.githubusercontent.com/38491307/49805112-67cfdc80-fd65-11e8-9623-6c33c7aaaf69.PNG)
![1](https://user-images.githubusercontent.com/38491307/49805116-6999a000-fd65-11e8-9af5-03931eb3c9f0.PNG)
![2](https://user-images.githubusercontent.com/38491307/49805120-6acacd00-fd65-11e8-8112-a85dac8c6071.PNG)
![3](https://user-images.githubusercontent.com/38491307/49805126-6c949080-fd65-11e8-95f8-8b68295e32f3.PNG)
![4](https://user-images.githubusercontent.com/38491307/49805172-859d4180-fd65-11e8-97ee-1f4121b9d0bc.PNG)

**Comment by ValentinaKopeva** [comment]
Done. 
1) Contract Couterparties is not full. User full this field

**Comment by michelebr76** [comment]
I am doing the test for loading some mistakes/comments:
![image](https://user-images.githubusercontent.com/37332394/50040122-ccc55400-003d-11e9-9b40-f054df6699ae.png)

- correctly loaded the "Number from file" but i was expecting this progressive number can be used as document number. We can do it? I think it will be better
- Can we also import the time (at the moment just the date)
- we need to work on "Tipo Documento" that is for digital invoice (and not should not be a selection but a field automatically filled) we see about Digital Invoice
- we need also to work on PAYMENT (the tablet register them and send them)

in addition when we have "k" operation, now is not registered at all (while before it was). Why it? Maybe the problem is the warehouse (before we did not have it).
About Warehouse, not clear how it works. We need to create warehouse common for both companies. Can we do it?

**Comment by michelebr76** [comment]
in addition: REGISTRATION OF PAYMENT
At the moment in the file uploaded in 1C we have no any registration of the lines regarding the PAYMENT (in file they are lines starting with INCASSI), like this:

incassi\|I\|001\|01\|00117\|00000249\|006\|07/12/18\|00000244     \|07/12/18\|00000126,570\|F\|00000000,000\|          \|08:41\| \|        \| \|    /  /  \|
--

Payment should be ABSOLUTELY LOADED IN THE SYSTEM.

the PROBLEM: according my understanding, in DRIVE we have two different document if payment is by CASH or NOT CASH and we need to define how to administrate it

In any case at the moment, we can manage all like CASH DOCUMENT (there is a particular situation connected with Check that we need to discuss with costumer)

Here the "Cash receipt" document
![image](https://user-images.githubusercontent.com/37332394/50042088-402b8d80-005f-11e9-9e93-bf9512cb9bab.png)

And here the excel with explanation
[Output - Payment.xlsx](https://github.com/asandulsky/1C-Italia/files/2682552/Output.-.Payment.xlsx)

Some comments:
- About IVA, not clear how it tracks it, but it should be got from Original document 
- Cash: at the moment we can all track from "Cassa Furgone 1". In future depending from Agent code it should be realized who is the user and how to put it
- in case of Type of document K, it should look to Sales invoice on PRO

**Comment by michelebr76** [comment]
We

**Comment by michelebr76** [comment]
I will send by email file + specification of the new file (based on DATA loaded by 1C) generated from the TABLET that should be loaded on 1C.

**Comment by michelebr76** [comment]
Regarding INPUT file. Basically is ok despite some little mistakes. In the attached document the check list and what should be corrected.

[INPUT FILE - Rev 1.docx](https://github.com/asandulsky/1C-Italia/files/2692483/INPUT.FILE.-.Rev.1.docx)

**Comment by michelebr76** [comment]
About OUTPUT file (from TABLET to 1C) I can send file for test that I have.
We need to check and remap the file and to add the INCASSI registration that we never tracked. In the attachment document the resume.

[OUTPUT FILE.docx](https://github.com/asandulsky/1C-Italia/files/2692553/OUTPUT.FILE.docx)

**Comment by michelebr76** [comment]
In order not to have problems with quantity of goods, it will be good to LOAD goods to temporary warehouse (truck).

Basically operation to be tracked is the following:
![image](https://user-images.githubusercontent.com/37332394/50188144-d7733800-0320-11e9-9c89-8ae957466713.png)

But it should be sent also to TABLET (see attached document about what to send)
[LOAD MOBILE WAREHOUSE.docx](https://github.com/asandulsky/1C-Italia/files/2692608/LOAD.MOBILE.WAREHOUSE.docx)

**Comment by michelebr76** [comment]
Looking at loaded data on the table, we noticed that or some Costumer (ANACLI lines) it has not been exported from 1C fields connected with Address. Not clear how it can be. happened (data re correctly registered in the system).

Here two example of lines (the first without, the second with....
I noticed that where we have addresss we have always a field "0000" and not clear why cause not correct

ANACLI|I|01|00000022|Baldino Libera|||||IT|IT01606130621|||Сontanti||||001||00003406341287|||||||||001|01|Baldino Libera Bar Roma|||||||||||||2|30|

ANACLI|I|01|00000026|Carbone Angela|VIA GIOVANBATTISTA BIANCO|82030|PAUPISI|BN|IT|IT01466490628|||||||||0000|||||||||||Carbone Angela Bar Caffè Fontana|||||||||||||||

**Comment by michelebr76** [comment]
Mistake in uploading the system from TABLET to 1C.

Test of uploading has been done in TEST Environment on computer of Client.

The file used for the test (provided by the costumer) is attached in ZIP
[AGE001.zip](https://github.com/asandulsky/1C-Italia/files/2736572/AGE001.zip)


[OUTPUT FILE - Rev 2.docx](https://github.com/asandulsky/1C-Italia/files/2736838/OUTPUT.FILE.-.Rev.2.docx)

**Comment by michelebr76** [comment]
updated checklist for loading info from tablet to 1C

[OUTPUT FILE - Rev 3.docx](https://github.com/asandulsky/1C-Italia/files/2746674/OUTPUT.FILE.-.Rev.3.docx)

**Comment by michelebr76** [comment]
PROBLEMS with CURRENCY in GRUPPO SIMON

We have a serious problems that not allow us to do a lot of activities and to import from TABLET.

There is a strange behaviour regarding currencies that it is possible to see looking at SALES invoice and looking at contracts for different counterparties.

Look pictures:
![image](https://user-images.githubusercontent.com/37332394/51131657-a824ed80-1830-11e9-8ffd-a22b2ac1a792.png)

![image](https://user-images.githubusercontent.com/37332394/51131677-b541dc80-1830-11e9-8b39-ebac4310ca2e.png)

Basically no currency specified.
This problem can be solved deleting old contract and creating a new contract (Activties that user can do).

In this case we have later theoretically all ok.
![image](https://user-images.githubusercontent.com/37332394/51131895-37320580-1831-11e9-881b-26c86154f02f.png)

But when i try to post any sales document, despite it gives me EUR like correct currency, it return me a mistake for not correct exchange rate.

![image](https://user-images.githubusercontent.com/37332394/51131961-60529600-1831-11e9-85fb-26044782a161.png)

And we find this:
![image](https://user-images.githubusercontent.com/37332394/51132007-76f8ed00-1831-11e9-85a9-04e709bee4cc.png)

THE PROBLEMS IT SEEMS NOT CONNECTED WITH TABLET.

**Comment by michelebr76** [comment]
Maybe one of the reason of mistake is during the load of INCASSI (Cash Receipt).
It is strange cause actually all should be in EURO. I tried to put off the "multi currencies" but nothing happens and it just hide the fields (and we cannot even fix the mistake in this case)

![image](https://user-images.githubusercontent.com/37332394/51133435-43b85d00-1835-11e9-87d6-ba1624bdc891.png)

**Comment by michelebr76** [comment]
here another test file (much more simple). Same problems.

[AGE001.zip](https://github.com/asandulsky/1C-Italia/files/2756662/AGE001.zip)

**Comment by michelebr76** [comment]
I worked on the last file sent for upload. There are just 4 sales invoice and easier to identify mistakes.
Basically mistakes I notice are the following:
1) In **sales invoice** we have the following mistakes:

a) Impossibile to post the Sales Invoice cause of a mistake in "exchange rate" that is zero
![image](https://user-images.githubusercontent.com/37332394/51161791-21096100-1894-11e9-93e6-15f6926be1ff.png)
NOTE: not clear why there is an exchange rate, possibile mistake can be connected with "Cash Receipt" (see later). Problem can be manually fixed putting 1 and 1 as value

b) incorrect calculation of VAT.
Information are correctly loaded (22%) but the value of VAT is not correct. Not clear where it takes this info.
![image](https://user-images.githubusercontent.com/37332394/51161849-51e99600-1894-11e9-8e77-0c9f108708dc.png)

2) Mistakes in Cash Receipts (See photos)
![image](https://user-images.githubusercontent.com/37332394/51161849-51e99600-1894-11e9-8e77-0c9f108708dc.png)
not clear why it is not registering as euros

**Comment by michelebr76** [comment]
While you are working I am doing some check.
Basically i noticed that a lot has been done. I tried to check digital Invoice and for two documents Generated (here attached as ZIP) I got mistakes.
[Test Invoice.zip](https://github.com/asandulsky/1C-Italia/files/2759371/Test.Invoice.zip)

File ending with 154 returns a mistakes connected with the wrong VAT (it is effectiveness not correct how is managed the "IVA con rivalsa")
![image](https://user-images.githubusercontent.com/37332394/51177414-cdad0800-18bf-11e9-99ca-74a5c8f72f6b.png)


File ending with 155 has a mistake we already saw (round up) and fixing manullay all is ok
![image](https://user-images.githubusercontent.com/37332394/51177086-f54fa080-18be-11e9-954f-cc900cacbf48.png)

**Comment by michelebr76** [comment]
IMPORTANT: How to register in Digital Invoice the "OMAGGIO CON RIVALSA".
I checked and got information and it seems we find the solution.

In the attached ZIP there is:
- the actual file (generated from 1C) - ending with 154
- the file i modified (ending with 999)
[Digital Invoice - OMAGGI.zip](https://github.com/asandulsky/1C-Italia/files/2759628/Digital.Invoice.-.OMAGGI.zip)

There are several mistakes of round up that are already notifed.
I would like to give information how it should be managed the "OMAGGIO CON RIVALSA (with VAT charged)" and the "OMAGGIO (with VAT not Charged)"

Option one (that you find in file):
OMAGGIO CON RIVALSA (PRESENT WITH VAT CHARGE)

Correctly it is loaded and managed in 1C, but writing the Digital Invoice it should be changed a bit.

Here the changes:
- The line with the material should be written like a normal with VAT and no discount
- The system should create additional lines introducing the discount.

Line should be like this:
			<DettaglioLinee>
				<NumeroLinea>#</NumeroLinea> /-- Number of line
				<TipoCessionePrestazione>SC</TipoCessionePrestazione> /--Fixed value [SC]
				<Descrizione>OMAGGI CON RIVALSA</Descrizione> /--Fixed value
				<Quantita>1.00</Quantita>
				<UnitaMisura>ct</UnitaMisura>
				<PrezzoUnitario>4.92</PrezzoUnitario> /-- Value of the total amount of presents without VAT
				<PrezzoTotale>4.92</PrezzoTotale> /-- the same value of before
				<AliquotaIVA>0.00</AliquotaIVA> /-- Always zero
 				<Natura>N2</Natura> /fixed value
			</DettaglioLinee>


In addition, should be also addeded info in the final data:

			<DatiRiepilogo>
				<AliquotaIVA>0.00</AliquotaIVA> /-- fixed data
				<Natura>N2</Natura> /-- fixed data
				<ImponibileImporto>4.92</ImponibileImporto> /--  It should be the sum of all presents without VAT
				<Imposta>0.00</Imposta>
				<RiferimentoNormativo>OMAGGI CON RIVALSA</RiferimentoNormativo> /-- Fixed value
			</DatiRiepilogo>

**Comment by michelebr76** [comment]
I am doing test regarding the IMPORT of data from TABLET.
I know that it is work in progress, but i want to try to help

**Warehouse movement**
![image](https://user-images.githubusercontent.com/37332394/51200892-fe5e6300-18fa-11e9-9681-5bf090f3c74f.png)

I notice the following mistake:
- the operation as opposite direction like it should be. It should be FROM "Magazzino Principale" TO "The warehouse specified"
- the operation is registered like "Equipment sign-out" while it should be a simply TRANSFER (and for this reason there is the request of a GLAccount (while it should not be)
- there is just one line with not correct value (i think cause still not finished)

**Sales invoice**
![image](https://user-images.githubusercontent.com/37332394/51201547-a3c60680-18fc-11e9-83fc-c5ea99721bdd.png)
still there is the problems of the zero (i think already aware about it)

but when i fix it and i try to save, it returns me the following mistake
![image](https://user-images.githubusercontent.com/37332394/51201651-e4258480-18fc-11e9-9e41-40d021c719c9.png)

in other document, i noticed a mistake in "Payment Terms"
![image](https://user-images.githubusercontent.com/37332394/51202148-577bc600-18fe-11e9-9212-ca5a8dbad2ee.png)

I fixed both mistakes but not possible to post the invoice cause of this mistake
![image](https://user-images.githubusercontent.com/37332394/51202196-7d08cf80-18fe-11e9-80bb-2252a06fa512.png)

**Cash receipt**
It seems basically finished. I noticed that problem is the link to the sales file (that not being posted cannot be linked...)

![image](https://user-images.githubusercontent.com/37332394/51202690-99f1d280-18ff-11e9-8fad-7d764ca372a6.png)

**Comment by michelebr76** [comment]
We tested the interface with the Client and discussed about several points. In general is fine (despite not working at the moment the Digital Invoice) and there are two issues he asked to solve:

- To manage the creation of new Costumer that are inserted from TABLET (it happens sometime). Basically the TABLET send information using the file (i can give a sample). In any case, I told him it is not a priority at the moment.

- Number of documents: he insisted to have the number like in the Tablet but later i explained that this is a number of 1C... and he finally understand and changed is mind... but he asks in this case to change the field that actually is named "Number from file" with a format that should be like this:

"AgentCode/Number from file" (it means to add "AgentCode" and "/" before it).
it should be something like:
001/######
001/######

etc...

if we do like this, maybe we can even keep as standard the document number of 1C (at the moment we forced it to change adding a number)

**Comment by ValentinaKopeva** [comment]
![2](https://user-images.githubusercontent.com/38491307/51318014-2a4c2680-1a6a-11e9-8e46-4cfc2639aca7.PNG)
![default](https://user-images.githubusercontent.com/38491307/51318016-2a4c2680-1a6a-11e9-8db3-478f3378dfa6.PNG)
Error and example

**Comment by ValentinaKopeva** [comment]
[IT01620470623_00999.zip](https://github.com/asandulsky/1C-Italia/files/2768555/IT01620470623_00999.zip)
Example

**Comment by michelebr76** [comment]
The costumer notified some possibile problems that may occur during the identification of the product at moment of loading the product. We need to understand if the problem exists or no.

The problem: in the tablet products are identified by three fields (in BLACK) like in this example of line:
vnbolcor|I|001|01|00000114|00000002|K|14/01/2019|00001|MP01      |**01|02     |0000008**|kg|00000002,000|00000017,220|

in this case the three fields have the following value: 01, 02, 000008

During the import in 1C we use (this appears at the moment) just one of these three fields, while it will be good to use all three of them to avoid situation when we have one (or even 2) value that are the same.

M.

**Comment by michelebr76** [comment]
I load here a resume of little mistakes to be fixed.
Some are connected with others issues, but i put all here

[Gruppo Simon - Some mistakes and correction.docx](https://github.com/asandulsky/1C-Italia/files/2771967/Gruppo.Simon.-.Some.mistakes.and.correction.docx)

**Comment by michelebr76** [comment]
MISTAKE IN CREATION OF WAREHOUSE MOVEMENT in identification of the Product

Look at the image:
![image](https://user-images.githubusercontent.com/37332394/51444504-b5dae700-1cf8-11e9-9f68-e24b9384db19.png)

the mistake is connected with the change of the code used to identify the products (now it uses all the three fields).

**Comment by michelebr76** [comment]
System is working, but there are some mistakes to be fixed.
Will be open later issues on exact problem.
