### ISSUE TITLE
Price in negative in Supplier's invoice

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#18]
In several case, the costumer needs to insert registering supplier's invoice, some negative lines (to register for example ENSARCO, Contribution to the transport).

System doesn't allow to do it.

Example:
![image](https://user-images.githubusercontent.com/37332394/49113119-f4be6480-f294-11e8-9583-526aa5600186.png)

**Comment by ValentinaKopeva** [comment]
Need to add the ability to enter rows with negative amounts in the document "Sales Invoice"?
Did I understand correctly?

**Comment by michelebr76** [comment]
Yes. Can you?

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
What you need it for ?

I think that such a change in the database may lead to a malfunction of the base.

**Comment by ValentinaKopeva** [comment]
I close this question, since it will be incorrect to implement this
 task from the point of view of security for the database.

**Comment by michelebr76** [comment]
I am also afraid of it...  but costumer wants it... can we put it?

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
I tried on a test base to change the field " the price and the amount " to negative values. 
This led to the fact that this document can not be held. 
We will not be able to complete  this task.

**Comment by michelebr76** [comment]
We understand how to do:
- we should not put negative value of an article
- we should put special discount line (maybe the same like discount cards).

Can we?



Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it
