### ISSUE TITLE
Suppliers's code

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#19]
The costumers wants to manage the supplier's code.
When he is entering a Supplier's Invoice, he wants to be able to insert also the supplier's code. The fact is that sometime we have items that are the same, but purchased by different suppliers.

Theroretically this possibility it is included in 1C:Drive (we have the "Supplier prpducts") but not clear how to use them. (see photo) 
![image](https://user-images.githubusercontent.com/37332394/49113403-c2f9cd80-f295-11e8-91fb-d7aeb1b10bdb.png)

The best is if it is possibile to:
- have the possibility to use such suppliers products (that basically can be just a code) when registering an invoice 
- when we look the supplier's pricelists, it can be very good to show them

**Comment by ValentinaKopeva** [comment]
When you buy the same product from different suppliers, would you like to see in the purchase and sale documents, as well as in reports (for example, price list) from which supplier received the goods? (The supplier’s code field should be recorded next to the product name)

**Comment by michelebr76** [comment]
Instead of the name of supplier, he would like to see the “suppliers code” for such article.

To understand better, the same product can have different suppliers and each supplier use a different code. He would like to keep this info somehow in the article. Field should be optional and inserted when registering an Purchase invoice... 
I know it is not a big sense.. but he ask so





Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
When creating the "Supplier invoice" document, 
you must link the supplier's code to the purchased goods
Right?

**Comment by michelebr76** [comment]
Right 

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
This task can be realized only in the following way:
Create a product for each supplier.
supplier1 - product1
supplier2 - product2

**Comment by ValentinaKopeva** [comment]
Close this question. 
It is possible to implement only when you create your product for each supplier.
