### ISSUE TITLE
Printing forms: DDT

### ISSUE THREAD

**Issue by ValentinaKopeva** [asandulsky/1C-Italia#2]

**Comment by michelebr76** [comment]
This document it is mandatory by Italian law in case invoice and delivery of goods travel separately.

**Comment by ValentinaKopeva** [comment]
Is there any question on this Issues?

**Comment by michelebr76** [comment]
Let's close

Eng. Michele Brustia
Tel: +7 918 4113551
Email: michele.brustia@gmail.com
