### ISSUE TITLE
Info for Digital Invoice in counterpart

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#21]
Costumer wants to have the field for Digital Invoice and in particular he would like to have in counterparty the possibility to have the followin fields:

1) PEC (it is an email but with legal validity)
2) Code of Delivery from SDI

Such Info he wants already to have to start to insert

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49151927-5547b300-f322-11e8-95ee-8061f8b4da23.PNG)

In the сounterparties (photo) card you need to add 2 fields. 
PEC - multiline text field
Code of Delivery from SDI - text field
 Did I understand correctly?

**Comment by michelebr76** [comment]
PEC is a email address

Code of delivery: yes, text. Both we need also for e-invoice 

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49152831-10714b80-f325-11e8-9f2b-32d25186a552.PNG)
Could you get out of the infobase?

**Comment by michelebr76** [comment]
Strange. I went out time ago. Kill me

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49154153-c1c5b080-f328-11e8-8f76-d165cd79ddf6.PNG)

Done. Did you do it right?

**Comment by michelebr76** [comment]
Instead of Code of Delivery can you call it “SDI Code”

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49155322-b4f68c00-f32b-11e8-939c-4d5da258bf34.PNG)
Сorrected.

**Comment by michelebr76** [comment]
Good.

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
it was done but now missing fields. What happened?

![image](https://user-images.githubusercontent.com/37332394/50100483-eb377500-0220-11e9-8458-5e8de8409a75.png)

The same is the field "Codice Fiscale" that we asked to remove (And it was done)
![image](https://user-images.githubusercontent.com/37332394/50100519-fab6be00-0220-11e9-9f5c-9cb98e05371f.png)
