### ISSUE TITLE
Management of Payment

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#22]
It should be possibile to automatic manage the payments terms with some standard conditions that we have in Italy and it seems not inserted in the system.
This should be possible both in sales invoice and passive invoice.

At the moment we have just two possibilities:
- cash
- not cash

The not cash should have much more possibilities.
Condition we need to have (And also managed by E-Invoice should be as follow):

- RIBA: it is basically a way where the Bank is allowed to get automatically money for you (no any real action to be done, just we need to be able to insert the possibility to put RIBA)
- RID: it is another way, that for us nothing change expect the fact that we need to be able to select it
- Carta di Credito: Credit card

In addition (not depending from the  way of getting money), it should be possibile to have some standard situation of payment. In particular we need the following:
- 30 Giorni fine mese fattura: it means 30 days after the end of the month (e.g. if the invoice is issued the 14 of october, the payment day should be the 30 of November)
- 60 Giorni fine mese fattura: it means 30 days after the end of the month (e.g. if the invoice is issued the 14 of october, the payment day should be the 30 of December)
- Recursive monthly payment. In this case we need to be able to split in a defined number of paymenet and to create a calendar that we can automatically insert in the Cash flow.

Such conditions should works both in sales and purchase

**Comment by asandulsky** [comment]
We will add 
    RIBA,   RID,     Carta di Credito

some standard situation of payment
    this should be managed by contract terms. Drive doesn't have it. Some other programs of 1C can do it. There is a subsystem that we sell for an additional cost "Payment calendar" is doing exactly that.
It is not only the question of registering the dates we gave a client but also a reporting system that controls if payment was on time how has to pay today or tomorrow.

    we can not do it at 0 cost just because it is common in Italy. It is common in Russia also - it cost some extra money...

**Comment by michelebr76** [comment]
Ok. Please tell me price of this add on and let’s simply sell it

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
As I wrote in topic “Digital Invoice” we need to insert the exact list we need for it.

 


<ModalitaPagamento>


MP01

contanti


MP02

assegno


MP03

assegno circolare


MP04

contanti presso Tesoreria


MP05

bonifico


MP06

vaglia cambiario


MP07

bollettino bancario


MP08

carta di pagamento


MP09

RID


MP10

RID utenze


MP11

RID veloce


MP12

RIBA


MP13

MAV


MP14

quietanza erario


MP15

giroconto su conti di contabilità speciale


MP16

domiciliazione bancaria


MP17

domiciliazione postale


MP18

bollettino di c/c postale


MP19

SEPA Direct Debit


MP20

SEPA Direct Debit CORE


MP21

SEPA Direct Debit B2B


MP22

Trattenuta su somme già riscosse

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49516159-f9dd6e00-f8a9-11e8-8652-b170c2f65d80.PNG)
Check

**Comment by michelebr76** [comment]
Maybe we can put as “Code” the part: MP01 and so on (cose that we will use also in digital invoice) and to put name and full name like fields the first for print and selection form and the other just to describe better?

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
![23](https://user-images.githubusercontent.com/38491307/49538433-70935f00-f8dc-11e8-80fc-a9eaabc92a98.jpg)
Right?

**Comment by michelebr76** [comment]
Good 

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
I just checked now and we need to do a little change for future E-Invoice cause there is a situation (the cash payment), missing.

Basically, when a person select the "Cash" payment, there should be the option: 
MP01 | contanti

The code "MP01" should be tracked when we will work on Digital Invoice
