### ISSUE TITLE
Supplier's pricelists

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#23]
We have still the problem of the supplier's pricelists when we enter with italian interface.

The problem is JUST when we enter in ITalian and not in English or Russian.
We tried to check SMARCAT but it seems all ok, so not clear where is the mistake

![image](https://user-images.githubusercontent.com/37332394/49114854-829c4e80-f299-11e8-905f-fdedcf92a60e.png)

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49142351-9bdce380-f309-11e8-8b61-0f42430f7b6f.PNG)
If i understand you correctly, you you are talking about the report  "Listini del fornitore". It's working. (on photo) 
Please stick a photo of the step by step error.

**Comment by michelebr76** [comment]
Yes. This, it works in English and Russian.

Please enter to system with following user: USER_IT
And try to do the same

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
What is a password of USER_IT?

**Comment by michelebr76** [comment]
No password

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
Info base “Mess” has USER-IT. And this user has the password.

**Comment by michelebr76** [comment]
Try with:
Login: Assistenza
Password: Michele76


Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
This bug is fixed, please check.

**Comment by michelebr76** [comment]
Good! Thanks, it works!

Which was the problem?
I think we have similar problems also in other system.

**Comment by ValentinaKopeva** [comment]
The problem was in configuration code.
