### ISSUE TITLE
Project PROXIMA MILANO - Not able to Invoice WORK

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#24]
In Drive it is not possibile to issue any invoice for WORK activites. Maybe it is a mistake of user, but actually it should be possibile to create an invoice in both case:
- when I did a quotation and an order and i need to charge them
- when I directly open a work order

It is possibile that there is another procedure.

**Comment by michelebr76** [comment]
For example. Go to the attached sales order (it is on the demo: assitech.1C-erp.it )

![image](https://user-images.githubusercontent.com/37332394/49137843-ec464800-f2ed-11e8-967f-8f17f3200f7b.png)

We need to be able to issue now an invoice.
When we try to do it, it doesn't show us the possibility include "Works" items, while for QUOTE and SALES ORDER i can use them.

**Comment by michelebr76** [comment]
The problems seems connected with the fact that WORKS have a different way to operate.
When we try to check and we try to issue an invoice, the system returns such message:

![image](https://user-images.githubusercontent.com/37332394/49138357-3c71da00-f2ef-11e8-9699-490101c6d7dc.png)

Telling that all it was invoiced before.

**Comment by michelebr76** [comment]
Any news? We need to do a video for costumer for this project and we need to show the invoicing of works.

**Comment by ValentinaKopeva** [comment]
May you send me photo. What is  the button you press, when this message is showing

**Comment by michelebr76** [comment]
Photo I added. 
I just try to do an invoice and not possibile. Can you try yourself 

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
Ok, I’m working of this question

**Comment by michelebr76** [comment]
Hello, any news about it? We needed to prepare a working demo for the costumer 1 week ago... but without the possibility to invoice "works" we are blocked...

**Comment by ValentinaKopeva** [comment]
This bug is fixed

**Comment by ValentinaKopeva** [comment]
Check it please
