### ISSUE TITLE
Discount line to be added in invoice (sales and suppliers)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#25]
The costumer has still need to register some "discount" (originally was opened ad "negative valute" of items) that are lines to be added with a value that can be a % or a fixed value.

In attachment a document that has this situation::
[FT ACQUISTO TIPO.pdf](https://github.com/asandulsky/1C-Italia/files/2626497/FT.ACQUISTO.TIPO.pdf)

Maybe we can create an additional table of discount to be loaded?
We have at the moment the possibility to load: Products, Services and we can have a table discount where the value inserted (that are basically additional lines) can be or discount by % or fixed value.

What do you think? Some how we need to solve the situation cause the costumer cannot register invoice (he has always this lines).

**Comment by asandulsky** [comment]
it is a purchase process. If a supplier gives a discount you just record in 1C final price, the actual amount that was paid. 

if we add a new function to document to track discount from supplier how do you want to use this information? do you need reports that can analyse it?

**Comment by michelebr76** [comment]
Theoretically we don’t need to track separately, it should be just considered as a discount.


Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by asandulsky** [comment]
if we don't need to track why spend the time to make it?

it is forbidden to have lines with negative values.

we need to understand the problem to propose a solution

**Comment by michelebr76** [comment]
This is a field MANDATORY also for Digital Invoice. We need it to have for sure.

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it
