### ISSUE TITLE
Issue of first Digital Invoice for 1C-ERP

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#28]
It has been created the sales INVOICE to Costumer MAS.
This is a real invoice with all real data.

In case of change (it can be even a test itself) once issued the E-Invoice, we will need to issue a Credit note (and maybe we can even try to do it....)

The document you can find in the 1C-ERP system.
[Sales invoice 1 datato 29.11.2018.pdf](https://github.com/asandulsky/1C-Italia/files/2628134/Sales.invoice.1.datato.29.11.2018.pdf)

We need now to start to put the right data in order to create the correct XML.

At the moment, I see that CREATE XML is connected with sales invoice, while in the future it will be better to move to "TAX INVOICE" cause the process we would like to have is:

QUOTE -> SALES ORDER -> later company can prepare one of the following documents) 
a)  GOODS ISSUE (Documento di Trasporto): it is a document of delivering goods (not an invoice)
b) SALES INVOICE

After it company should take the GOODS ISSUE and the SALES INVOICES and issue a TAX INVOICE.
This TAX INVOICE should be the base of the XML.

This is the process, but we can now work on SALES INVOICE cause it is fine for the moment.

**Comment by michelebr76** [comment]
Here fields we need to put in XML (i think you already have, but let's check).
**IDTrasmittente**: it should be in our case IT + our INN (P.IVA in Italian).
Info are already in company info.

**ProgressivoInvio**: it should be a progressive number. Being the fist, it can start from zero... 

**FormatoTrasmissione** : being a company it should be: **FPR12**
NOTE: this is DEFAULT value.
It can be very good if we will put (in all drive installation) a flag where at counterpart level we can specifiy if it is a "Pubblica Amministrazione" (in this case the vaule should change to FPA12).

<CodiceDestinatario>: in this case should be 0000000 cause the costumer did not have a SDI Code (yesterday we added it in MES). Can we do automatically that if the "SDI Code" is not valorized it writes "000000"?

<ContattiTrasmittente>: telefon and email of the company issueing the invoice (in this case us). The fields are valorized

<PECDestinatario> we addedd this field yesterday in MES, it should be also in other Drive and in our case at level of Counterpart.
IMPORTANT: this value should be valorized JUST if the CodiceDestinario is "0000000"

**Comment by michelebr76** [comment]
I continue with description of field and what to put (just to check)

**<CedentePrestatore>**
All these fields (mandatory) should be received automatically from Company information.
NOTE, there is a little difference between Italian and English...
INN: is translated as P.IVA (this is a key number and the most important in italy)
VAT Number: is translated as CODICE FISCALE

Usually (90% of companies) the 2 code are the same.

Some field maybe NULL
 <RegimeFiscale> it has been created a list that it should be put in Company Info (not needed to change for each document cause it should be fixed).
Can we put the selection lists (it will be good if also with descritipion) we can put to be selected when we choose the "account policy" of the company.
In any case, at the moment, for us and all our costumers is: **RF01**

**<Sede>**
It is legal address... in our Case: Via Circonvallazione 58, 28043 Bellinzago Novarese (NO)
the one in milan is operative address

 <StabileOrganizzazione> NULL and also for our company will be so. We don't plan in early future to use it.

<IscrizioneREA> this field we should valorize (Also for some company) but not all fields.
Our number is: NO - 244418 
but actually, there are two part:
<Ufficio> = NO
<NumeroREA> = 244418
Other fields:
<CapitaleSociale> we need to introduce this value in the Company Details (not mandatory for all)
<SocioUnico> can we put a list where to select the two options?:  SU] : socio unico
[SM] : più soci
<StatoLiquidazione> we can even put for all companies a standard field: **LN** (it means that it is not closing)

<Contatti> to be taken from Company details

**Comment by michelebr76** [comment]
I continue

<RappresentanteFiscale> NOT NEEDED (we will implment just in case we will have such case)

 <CessionarioCommittente> data of the counterpart. In part similar to the one we have before, we need to change the counterpart catalog according the required fields


<TerzoIntermediarioOSoggettoEmittente> WE DON'T NEED IT 

We go to the body
 <FatturaElettronicaBody>

<TipoDocumento> depends on type of document.... i sent already the list (i underline our case now):

**TD01 | fattura -> INVOICE**
TD02 | acconto/anticipo   su fattura -> INVOICE FOR ADVANCE PAYMENT
TD03 | acconto/anticipo   su parcella (we usually don't need it)
TD04 | nota   di credito -> Credit note
TD05 | nota   di debito -> Debit not
TD06 | parcella (we usually don't need it)

I think no problem to put it automatic depending on document.

Other fields are clear i think.

This field: <DatiRitenuta> we don't need now.

<DatiBollo> I am waiting info from our account what to put...

<DatiCassaPrevidenziale> not needed

 <ScontoMaggiorazione> this are the famous one we need also to create for MES (the discount on document). we need to manage them... in this case, we don't need.

<Causale> This is a text... i think we need to have a field we can put... 
<Art73>not needed for us and even for our costumer

Later some data we need to work on that are not mandatory... if you want we can even work on it... they are about transport. at the moment in any case not needed.

<DatiBeniServizi>
Here i think you already put to get data from invoice... tell me if there is a problem.

<DatiVeicoli> not applicable now... maybe in future

<DatiPagamento>
I think mainly data are clear. About this field:
<ModalitaPagamento>
i sent time a go a list... and it should be a list valorized for each document (also quote, sales order and so on) in the payment details. It is what asked in project MES

NOTE: i saw that you create the field with all value: CausalePagamento, this is applicable just in some case (payment with RITENUTA) and usually not needed

**Comment by ValentinaKopeva** [comment]
May you cheсk it, please?

**Comment by ValentinaKopeva** [comment]
[IT02569340033_00021.zip](https://github.com/asandulsky/1C-Italia/files/2629000/IT02569340033_00021.zip)

**Comment by ValentinaKopeva** [comment]
Have you cheсked ".xml"?

**Comment by michelebr76** [comment]
It returns the following mistake:

 

le non conforme al formato (nella descrizione del messaggio Ã¨ riportata lâ¬"indicazione puntuale della non conformitÃ ) - La versione indicata in fattura non è presente tra quelle ammesse

 

https://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/AccediAlServizioAction.do?pagina=controlla_fattura

 

I checked and for sure this code is not right:

<CodiceDestinatario>999999</CodiceDestinatario>

 

At least should be 0000000

But in that case it is needed to have the PEC (and we don’t have it… but temporary MASSRL@pec.it <mailto:MASSRL@pec.it>  )

 

 

Also wrongly valorized the Provincia in our date

It is: <Provincia>MI</Provincia>

It shoudl be: <Provincia>NO</Provincia> (it was written wrong…. Cause written full… we need to put a list… to be sure people will not do mistake)

**Comment by michelebr76** [comment]
YES, i did and just wrote the mistake i noticed.

 

M.

**Comment by ValentinaKopeva** [comment]
You meen in case we have  Provincia=MI we should make in .xml Provincia=No?

**Comment by michelebr76** [comment]
Yes. But it should be automatic. 
I can send you list of province of Italy and can you put it? This for future

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
Yes. I wait list of province .

**Comment by michelebr76** [comment]
Ok. I will prepare and send you.
For the moment put MI

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
Ops: put NO

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
Ok

**Comment by ValentinaKopeva** [comment]
provinci is Alfa code 2
![1](https://user-images.githubusercontent.com/38491307/49226991-146e9d80-f3f9-11e8-84f2-885b96ea5177.PNG)

**Comment by ValentinaKopeva** [comment]
[IT02569340033_00022.zip](https://github.com/asandulsky/1C-Italia/files/2629410/IT02569340033_00022.zip)
Right .xml with "NO" and  CodiceDestinatario " 0000000"
Check it, please?

**Comment by michelebr76** [comment]
Now i will check.

Here the list of Province of ITaly.
Can you put it

**Comment by michelebr76** [comment]
Not working. I check now why…. It returned me the same mistake…

But I noticed in any case the “Codice Destinatario” has just 6 digits while it should be of 7: 0000000

**Comment by ValentinaKopeva** [comment]
[IT02569340033_00022.zip](https://github.com/asandulsky/1C-Italia/files/2629487/IT02569340033_00022.zip)

**Comment by michelebr76** [comment]
Still mistake. It mention that there is a mistake in the version used, maybe something should be changed? Maybe the name.

 

 

In addition:

at level of items (body of invoice), i see some part that we need to change (but not sure this is the mistake)

<NumeroLinea>1</NumeroLinea>

<Descrizione>1C:Drive pack.  (Server  (x86-64) + 5 license simultanee)</Descrizione>

<Quantita>2</Quantita>  ->> it is possibile to put the decimal (separated by the “.”) it should be 2.00

<UnitaMisura>pcs</UnitaMisura>

<PrezzoUnitario>5000</PrezzoUnitario>it should be 5000.00

 

It is missing the “discount”…. In fact there is not correspondence with the total

 

Line should be:

<ScontoMaggiorazione> Value [SC] (cause it is a discount) if is a markup should be [MG]

<Percentuale>30.00

<Importo>1500.00

 

<PrezzoTotale>7000</PrezzoTotale>it should be 7000.00

<AliquotaIVA>22</AliquotaIVA> it should be 22.00

 

And so on..

**Comment by michelebr76** [comment]
Good morning, I would like to know when we can proceed further on this topic.
