### ISSUE TITLE
Insert the field "Supplier's code"

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#29]
We need to isnert in the form for Supplier's price also the possibility to add Supplier's code.

**Comment by ValentinaKopeva** [comment]
I can insert the “Supplier Code”  column by 
repor (photo)  , but this column will consist of the last register entries.

![default](https://user-images.githubusercontent.com/38491307/49223720-9f976580-f3f0-11e8-8b69-9e570d29d667.PNG)

**Comment by michelebr76** [comment]
Entries will be connected to the supplier?
