### ISSUE TITLE
Not working "Print Form" in Gruppo Simon

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#30]
In MES, is not working print form. Look the mistake.

![whatsapp image 2018-11-29 at 13 05 26](https://user-images.githubusercontent.com/37332394/49222476-46253b80-f3dc-11e8-9f23-d69848dd8721.jpeg)

I think that in MES there are missing several "standard" lists... can you take a look?

**Comment by asandulsky** [comment]
We need to update language first.

Is language in demo good to copy to mes project?

**Comment by michelebr76** [comment]
Yes. You can copy to:
- mes
- 1C-Erp
- Proxima MILANO

These are demo can be good to have updated as language 

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it
