### ISSUE TITLE
Gruppo Simon - Create automatic export of Sales invoice

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#34]
It is needed to create an automatic data processor that will automatic export in pdf all the invoices issued in a definend period (usually a month).
Pdf file should be exported to a folder on the pc.

**Comment by asandulsky** [comment]
it is at clients cost - 2 hrs of work

**Comment by ValentinaKopeva** [comment]
![Image](https://i.imgur.com/HS44xo8.jpg)![Image](https://i.imgur.com/axwtUKz.jpg)![Image](https://i.imgur.com/lqA067u.jpg)![Image](https://i.imgur.com/da4CZLR.jpg)![Image](https://i.imgur.com/wfF9cqU.jpg)

**Comment by ValentinaKopeva** [comment]
Instruction for this matter
