### ISSUE TITLE
Different Prefix for documents depending on issuer

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#41]
This issue involves partly the interface with agent system.
Depending from the department issuing a document (each user should be linked to one department) the prexis should be different.

At the moment we have three situation:
- Ufficio Centrale: Prefix: 0001
- Terminale 1: Prefix: 0002
- Terminale 2: Prefix: 0003

**Comment by ValentinaKopeva** [comment]
![_rmwk61qw1c](https://user-images.githubusercontent.com/38491307/49536562-e34e0b80-f8d7-11e8-9fc8-cb634fa94cc8.jpg)
![j2hrw3vizxm](https://user-images.githubusercontent.com/38491307/49536563-e34e0b80-f8d7-11e8-864b-6e8bfde2cb86.jpg)
Check, please.
Prefix of department in number of "Sales Invoice" ONLY assign after "-". 
For example start code  "0000-000001".
 If in Department, Prefix = 1111, THEN new code is "0000-111101".(on photo example from MES"Sales Invoice")

**Comment by michelebr76** [comment]
It has been done, but maybe it is the reason that create problems in number of Sales invoice.
To check the problem: go to sales invoice and press "save" or "post" and you will see that it is automatically changed the number of invoice
