### ISSUE TITLE
Search by supplier's code - DEACTIVATE FUNCTION OF SUPPLIER'S CODE

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#47]
When inserting a supplier's invoice, it should be possible to select the items by supplier's code.

**Comment by ValentinaKopeva** [comment]
Done

**Comment by michelebr76** [comment]
The field "Supplier's Code" is not working exactly as the costumer wants and actually it is not needed cause there is an option in DRIVE that substitute it.

Can we deactivate it?
