### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#48]
There are some fields that are not translated in Italian and should be fixed.

Here photos and missing translations:

In "Sales" sections
![image](https://user-images.githubusercontent.com/37332394/49880770-1f7bf180-fe2d-11e8-9525-125d5d4ca7a8.png)
ZagruskaInvoice -> **Importazione Documenti di Vendita**

In "Sales invoice"
![image](https://user-images.githubusercontent.com/37332394/49880977-88636980-fe2d-11e8-97e0-40ebe593ab1b.png)
Several words not translated:
TipoDocumento = Tipo di documento (this field actually be automatic valorized and not by selection)
RegimeFiscale = Regime Fiscale (this field actually be automatic valorized and not by selection)

GenerateAgent = Calcolo agenzia
and also down at the end
![image](https://user-images.githubusercontent.com/37332394/49881129-de381180-fe2d-11e8-8d42-aa78fdfd5b3e.png)
I.V.A. should be:

Going to CONTRACTS
![image](https://user-images.githubusercontent.com/37332394/49881183-0889cf00-fe2e-11e8-8607-bbe7ca16bcef.png)

AgencyContract = Contratto con agente
AgencyPercent = Commissione Agente

**Comment by michelebr76** [comment]
Before i did not put how to translate: I.V.A. that in english is written like SALE but i don't understand what exactly is...

**Comment by ValentinaKopeva** [comment]
![2](https://user-images.githubusercontent.com/38491307/49934566-c620ca80-fedf-11e8-9277-bc7c7341049a.PNG)
![3](https://user-images.githubusercontent.com/38491307/49934564-c620ca80-fedf-11e8-8ccd-2609685b2455.PNG)
![1](https://user-images.githubusercontent.com/38491307/49934565-c620ca80-fedf-11e8-8933-a0abbdb92251.PNG)

**Comment by michelebr76** [comment]
About this point, we will review all translation when finished the rest.

**Comment by michelebr76** [comment]
Closed
