### ISSUE TITLE
Mistake in calculation contributo di trasporto

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#49]
Not working properly: it is deducting JUST VAT, while it should deduct BOTH FIELDS:
VAT and CONTRITBUTE

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49933815-ba340900-fedd-11e8-93f4-17d8195a3967.PNG)

Imponibile = sum without VAT
Totale importo = sum with VAT
Netto a pagare = sum with VAT - Contributo transporto  
Mistake in Netto a pagare?? 
Netto a pagare = Imponibile  - Contributo transporto?

**Comment by michelebr76** [comment]
It is not calculating the 600 euro of transport contribution (just the vat connected with it)

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/49941917-e6a74f80-fef4-11e8-8e29-d80841e8d0ae.PNG)

**Comment by michelebr76** [comment]
I cannot now check on the system. Please check if everything is correct as value, with the one registered in the original document (that is stored in file)

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
Calculation of Contributo di trasporto is now correct, but the final value of the invoice (the one to be paid) is the final one:

Look the attached document. The value of the document should be: EURO 25.954,90 (and not 26.523,48)

![image](https://user-images.githubusercontent.com/37332394/50101729-a52fe080-0223-11e9-8572-079e63b7c0e8.png)

**Comment by michelebr76** [comment]
In addition also the final amount is not correct.
Now I wil check also, but look the attached invoice.... the final value are not correct.

[188-v51 del 08-03-2018.pdf](https://github.com/asandulsky/1C-Italia/files/2687072/188-v51.del.08-03-2018.pdf)

**Comment by michelebr76** [comment]
I am checking this issue. There are some strange figures even from original document.
In order to read better the document and to be used also for other costumer can we change position of the elements according this picture:

![change supplier s invoice](https://user-images.githubusercontent.com/37332394/50134470-62f0b880-0290-11e9-85b2-791ad57d3c05.jpg)


1) Invert the two fields (value and %) of the Contributo di trasporto
2) Move these two fields UP (before imponibile)
3) Contributo di trasporto -> Call it: SCONTI ADDIZIONALI
4) Imponibile should be calculated like the total amount - Contributo / Sconti 


NOTE: this will not fix the problem, but at least we will understand what to do...
the main problem is itself the original document.

We need in any case to have a way to manage discount also for other projects

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50137204-89701d00-02ab-11e9-8f13-ed51f1f5beba.PNG)

**Comment by michelebr76** [comment]
Opened an issue (in incoming) resuming which is the mistake.
