### ISSUE TITLE
Load of information to Tablet

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#50]
We already shared the technical information (in Italian) to speed up the process I will resume some instructions.

[Tracciati_TvCe_Android_6.095.pdf](https://github.com/asandulsky/1C-Italia/files/2673632/Tracciati_TvCe_Android_6.095.pdf)

The track for loading should be like the following:

Nome_tabella|I|field1|field2|field3|…
 (Value "I" that is for input, is always to be inserted)
Separation between fields is with character "I"

There should be only a file.
The name of the file should be:
AGE + agent code+ .DOS

In the excel file i send, there is the main info for creating the input table.
[Input Tablet.xlsx](https://github.com/asandulsky/1C-Italia/files/2673683/Input.Tablet.xlsx)

In addition we need to prepare the sharing of data for LOADING from warehouse (we need a bit to check, cause theoretically we need to track the movement from general warehouse to mobile one).

[Loading warehouse.xlsx](https://github.com/asandulsky/1C-Italia/files/2673709/Loading.warehouse.xlsx)

for the rest, we need to work on Sales invoice registering but also with payment register (the load file we worked on).

**Comment by michelebr76** [comment]
There are some mistakes in the file generated.
Here a lists of the one i noticed:

1) Missing simbol pipe "|" after the "i" in the line about Costumer. Look an example (before IT we should have "|")

ANACLI\|IIT\|\|\|\|\|   82030\|0\|00-000225\|\|\|\|\|0\|FRAMIC SRLS \|\|\|VIA FRASCIO   19\|\|\|\|\|\|\|\|\|\|\|\|\|\|IT01620480622 \|\| BN\|FRAMIC SRLS \|\|00\|\|\|\|\|\|\|\|
--
2) Costumer number has maximum 8 digits (not 9 like here: 00-000225) and can be very good if we don't consider the character "-"

3) Not clear why often we have field "ITALIA" while it is not needed and maximum we need to have "IT"

4) The mastro cliente should be or "00" or maybe it is better to put "01", now it is just 0 (while better to put both digits)

**Comment by michelebr76** [comment]
Also for CERANA (products lists), i notice several mistakes:

Cerana\|I0530\|00-00000007\|00-00000007\|MISCELA   GUSTO\|MISCELA GUSTO\|kg\|\|\|\|\|22%\|
--


1) Missing pipe symbol "|" after letter "i"

2) confusion with Mag Group, Mag Code and Mag_de
these three elements should define the products on the tablet (and allow us later to write back when uploading).
we already did it correctly in uploading (at least i think so, now something strange).

How should work:
each article has a PRODUCT ID (better to work on it) that for example can be AA004900204b
Product ID should be split in three fields: |AA|00490020|4b
- first two digits: AA
- second 8 digts: 00490020
- third 8 digits: 4b

In case of shorter code of the product, should be nothing.

We can also use the code of the products "00-000xxxx" if you prefer in some case, but the most impotant is: we need to use a system to recognize the products

**Comment by michelebr76** [comment]
To help you, I created these files with a kind of a checklists of mistakes I noticed.

Input FILE:
[INPUT FILE.docx](https://github.com/asandulsky/1C-Italia/files/2688059/INPUT.FILE.docx)

About OUTPUT FILE: when we will load the input, we will get the OUTPUT file but with a bit different fields so we need to check out. At the moment we had file from old agent system.

I already opened a issue about some mistakes (maily payment)

**Comment by michelebr76** [comment]
1.
 
When you load data you have a client list in Tablet AND a client list in 1C - you need to map this two lists
 - to map we have a field that you need to fill - right now you did not do it for ALL clients and you get errors
 - when the system can not find a matching client - it opens a dialog to fil it. make sure you don't just close it - fill all
 
CLEAR.
Question: in case the client is new (created in the tablet), it is possible to the possibility to create it? Or at least to have the button “CREATE” near by?

2.
When you load data you have a Product list of 1C and the Product list of Tablet - you need to map this two lists
 - to map we use ProductID
 - if the system doesn't find the matching product it will open a dialog to select - you need to select for all. Don't just close it
 
SAME LIKE ON POINT 1
Possible to have also button CREATE PRODUCT?

3.
There is a field PERTITE (it is PARTITE)
we don't understand what is it and DID NOT provide us with info about it. If you did - please send again, because we did not get it
 
I SENT INFO TIME AGO, BUT BETTER TO EXPLAIN EVERYTHING AGAIN CAUSE “PARTITA/E” IS A COMMON WORD YOU WILL OFTEN FIND IN ITALY IN ACCOUNTING WORLD.

Partita (in plural “Partite”) contabile (but this word is usually not mentioned) it is a common word and can be basically translate as “accounting record”.

In the case of the TABLET we are interested just in the “PARTITE APERTE” (OPEN ACCOUNTING RECORD). We consider “open” all the records that are not fully settled (e.g. a sales invoice not fully paid). It means that basically we need to track all the sales invoices (we don’t use other sales document with the tablet) that are not fully paid (but consider alwayas that we have 2 companies).
According the line created by the system, it seems fine what it has been done by Valentina but we need to avoid to write lines in case of FULLY SETTLED document (cause in future we will have simply too many lines written). It means that should be created a FILTER that will not consider the settled document. 


4.
In the table INCASI (“INCASSI”) we have information about the amount paid
BUT in that table, there is no Client code or Invoice Code
we can not clearly identify who paid
we can not map it with invoice automatically
we wait for the info what to do

INCASSI table track JUST “cash receipt” document (no other way of payment).
Client and Invoice code there are in the track and it was send information (maybe they have been lost)
Here a sample of one line and I will write again all fields:

incassi|I|001|01|00117|00000249|006|07/12/18|00000244    |07/12/18|00000126,570|F|00000000,000|          |08:41| |        | |  /  /  |

Using this samples I explain what they are:
Incassi 		 table name (fixed)
I 		fixed value (not important)
001		AgentCode (it allows us to understand who registered the operation using the Agent Table)
01		MasterCostumer – we don’t use it and we put it as fixed as 01
00117		Client Number – it should be already been mapped before registering the documents
00000249	Document Number (it should be the number of the Cash Receipt)
006		Row of payment. Not clear how it is defined by the TABLET but theoretically we can even not use in 1C creating more cash receipts
07/12/18	Date of the cash receipt
00000244	Sales Invoice number (attention: we need to define exact rule to have same sales document in Tablet and 1C (I write down my consideration about it)
07/12/18	Date of the Sales 
126,570	Amount of the payment
F		Type of document (we can have: “F” = Sales invoice of IMP; or “K” = Sales invoice of PRO) (the same like in Sales document…)
Empty
08:41		Time of the Sales receipt (it is important to understand how was organized the sales)

DOCUMENT NUMBER - IMPORTANT
There is an important issue already explained several time and requested by the costumer: documents should follow defined rules for number to avoid problems (cause we have an offline tablet and we can have double numbering).

In 1C documents (e.g. SALES INVOICE) have the following format of number: 0000-00000000

Registering document from the tablet can we have the following format

First part (PREFIX) = Should be the AGENTCODE (001, 002, 003…. Naturally we will have one zero more)
Second part = Should be the Document Number from the tablet (that it is a progressive number).
This will help us also to find document when we registered INCASSI

Example:
Agent 001, register Sales invoice (Code “F”) number 000456, 000457 and also Sales Invoice (Code “K") 000123 in tablet
Agent 002, register Sales invoice (Code “F”) number 000134 and also Sales Invoice (Code “K") 000034, 000035 in tablet

Result should be:

Sales Invoice created on IMP: 0001-00000456, 0001-00000457, 0002-000000134 (all should be with DATE and TIME from TABLET)
Sales Invoice created on PRO: 0001-00000134, 0002-00000034, 0002-000000035 (all should be with DATE and TIME from TABLET)

Naturally INCASSI (cash receipt) and PARTITE (unsettled document) should be tracked according this rules.

**Comment by ValentinaKopeva** [comment]
1.Question: in case the client is new (created in the tablet), it is possible to the possibility to create it? Or at least to have the button “CREATE” near by?
2.Possible to have also button CREATE PRODUCT? 
1,2 Question  (on photo )  button "PLUS" add product and client 
![default](https://user-images.githubusercontent.com/38491307/50396628-2e8f6780-077c-11e9-837d-49108eda82a1.PNG)

**Comment by ValentinaKopeva** [comment]
3. PERTITE  - DONE
In system now we have  4 "SALES INVOICE"
![default](https://user-images.githubusercontent.com/38491307/50398152-72876a00-0786-11e9-8c97-1e5d8033c52f.PNG) 
1) 0000-100042 -  the document has no payment PARTITE|I|01|0000168|P|0000100042|18.12.2018|||||||||0,74|
2) 0000-100005 the document has payment  (
paid in full line is not unloaded) 
3) 0000-100041 - This document is partially paid 
PARTITE|I|01|0000168|P|0000100041|05.12.2018|0,24||||||||0,74|
4) 0000-100032  the document has no payment 
PARTITE|I|01|0000038|P|0000100032|12.11.2018|||||||||138,06|

**Comment by ValentinaKopeva** [comment]
4)  INCASI  - DONE 
Create "Cash Receipt" based  of "Sales Invoice"

**Comment by michelebr76** [comment]
In the following table, in RED the mistake

[IMPORT.xlsx](https://github.com/asandulsky/1C-Italia/files/2714376/IMPORT.xlsx)

and here the explanantion and what should be done.

[INPUT FILE - Rev 4.docx](https://github.com/asandulsky/1C-Italia/files/2714378/INPUT.FILE.-.Rev.4.docx)

**Comment by michelebr76** [comment]
There are still several mistakes that should be fixed in the TABLET.

In attachement files:
- AGE001.DOS: file exported from 1C
- [TEST IMPORT-MB.xlsx](https://github.com/asandulsky/1C-Italia/files/2735646/TEST.IMPORT-MB.xlsx) the excel version of the file with in red mistakes, in yellow correction required and some comments
- [Tracciati_TvCe_Android_6.095.pdf](https://github.com/asandulsky/1C-Italia/files/2735444/Tracciati_TvCe_Android_6.095.pdf): in this file (sent several time) there are all field and lenght of field. I know that is in Italian, but the lenght it is possibile to understand
- Mistakes returned ![20190107_142230](https://user-images.githubusercontent.com/37332394/50817275-979de000-1323-11e9-884c-708938046792.jpg)
- Checklists of what it should be done
[INPUT FILE - Rev 5.docx](https://github.com/asandulsky/1C-Italia/files/2736530/INPUT.FILE.-.Rev.5.docx)

**Comment by michelebr76** [comment]
I send you test I did
[Check.xlsx](https://github.com/asandulsky/1C-Italia/files/2744578/Check.xlsx)

and updated check lists
[INPUT FILE - Rev 6.docx](https://github.com/asandulsky/1C-Italia/files/2744579/INPUT.FILE.-.Rev.6.docx)

**Comment by michelebr76** [comment]
I did all check.Here the file with the mistake (in yellow some lines we should not load).
[CHECK-INPUT.xlsx](https://github.com/asandulsky/1C-Italia/files/2751339/CHECK-INPUT.xlsx)

Info in this file
[INPUT FILE - Rev 7.docx](https://github.com/asandulsky/1C-Italia/files/2751340/INPUT.FILE.-.Rev.7.docx)

**Comment by michelebr76** [comment]
Test of upload was basically ok. There are some little strange stuff (letters) that maybe is of the tablet. I asked to check.

There is for sure a mistake from us that is connected with the following costumer:

ANACLI|I|01|00000168|Amodio Capozzi|CONTRADA PEZZAPIANA|82100|BENEVENTO|BN|IT|IT01640670624|||MP01||||001|||||3000|3498880801|||||||||001|01|Amodio Capozzi Anema e Pizza||||||||||||001|2|30|

There are two lines in the file...
