### ISSUE TITLE
Digital Invoice - automatic printing (and sending if possibile of pdf invoice)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#51]
Costumer is proposing to add an interesting and VERY useful feature at Digital Invoice:

When we click to "Generate XML" automatically we will have also the print of the invoice (in pdf) and can be very good even the sending (at the email of the counterpart).
This is very interesting for all costumers considering also that the XML (that once generated is legally valid) is hardly possibile to be read

**Comment by michelebr76** [comment]
This activites can be scheduled till the end of the year.

**Comment by asandulsky** [comment]
we planed exactly the same
as we have some time and budget
  - we will do the reading and sending by email
you can print all forms you need right now
  - we will do the same in digitall fattura form

you can view incoming xml in normal form before loading (we did it already)
if you put xml in a folder - refresh incoming - select in a list and open it
you will see what was sent to you before loading it in to drive db

**Comment by michelebr76** [comment]
Future improvment planned. now closed
