### ISSUE TITLE
Setting up: Fattura Elettronica for Gruppo Simon

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#53]
We need to set up Gruppo Simon digital invoice for testing it on beginning of the next week.

Some specifications:
Operation should have the following process:
- On "Sales Invoice" document there should be the "Crea Fattura Elettronica" button
- Pressing it we will perform the following operation (should be possible just once)
- Creating the XML (According by law) that should be automatically loaded on the folder specificed by the user once (we need to create a place in setting where we can select the folder)
- It should also create the document "Fiscal Invoice" that will be stored on the system
- It should automatically create a PDF of fiscal invoice that will be stored in a folder specified by the costumer
- later on (not needed yet next week but in january should work) it should be send directly the pdf of the fiscal invoice to the costumer (using the email specified in counterpart)

This is the process to be performed.

Later on, there are some fields that should be not to be selected but automatically specified.
In particular in the Sales invoice, they are:
- Tipo Documento: i sent the list of type and depends exactly from the document we do (in this case a Sales invoice) - no selection should be here put and automatically defined
- Regime Fiscale: it is a standard depending from company, that we need to specify at that level (I sent a list about it)

![image](https://user-images.githubusercontent.com/37332394/50040248-3e9e9d00-0040-11e9-9da8-324169a9dea2.png)

**Comment by asandulsky** [comment]
we have a different procedure to what you wrote 
1. No tax invoice at the moment - just sales invoice
2. You go to Digital Invoice form and select all invoices you want to send. All invoices are stored in the 1c db and in outgoing folder
3. You can save outgoing and load incoming invoices from that form

- pdf will be created from here in the future. Right now there is another place to make pdf

+ Tipo Documento - is created automatically now
+ Regime Fiscale -  - is set up on Company set up page and is F01 by default

**Comment by michelebr76** [comment]
Ok. Consider that in future, we need to move to system of Tax invoice (this will be needed in future).

For now is ok.

 

 

M.

**Comment by michelebr76** [comment]
About Simon, there is not installed the “Digital Invoice” and actually i don’t know if we passed the test… I never received any file that passed it L

**Comment by michelebr76** [comment]
Some time ago it was send the attached file (this is the last i received) for Gruppo Simon.

I noticed several mistakes. I attach them.

[Some Mistakes of Digital Invoice.docx](https://github.com/asandulsky/1C-Italia/files/2744073/Some.Mistakes.of.Digital.Invoice.docx)

To quikcly check documents, I suggest to use the following excel file with all the lists of fields

[Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.xlsx](https://github.com/asandulsky/1C-Italia/files/2744080/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.xlsx)

**Comment by michelebr76** [comment]
I prepared a file with some comments to help to fix the file and the whole procedure (now is a mess for a user cause a lot of fields not in the right place)

[DIGITAL INVOICE - Comments.docx](https://github.com/asandulsky/1C-Italia/files/2744854/DIGITAL.INVOICE.-.Comments.docx)

**Comment by michelebr76** [comment]
After checking the new file created, I created this file.

[DIGITAL INVOICE - Comments-Rev 1.docx](https://github.com/asandulsky/1C-Italia/files/2746625/DIGITAL.INVOICE.-.Comments-Rev.1.docx)

There are several lines we will have to add (we did the minimum required but we need to include more fields)

**Comment by michelebr76** [comment]
Several stuff have been done. I did a test and noticed some mistakes. I send you updated document of what is needed.

**Comment by michelebr76** [comment]
I tested some digital invoices and sometime we have mistakes.

for example this (attached in zip cause i cannot in XML)
[IT01620470623_00274.zip](https://github.com/asandulsky/1C-Italia/files/2756676/IT01620470623_00274.zip)

Mistakes are these:
![image](https://user-images.githubusercontent.com/37332394/51134326-8713cb00-1837-11e9-90b8-7ccba739dd22.png)

Mistake 1 and 2: it should be 94.30 (instead of 94.3)
Mistake 3: it is just 6.... for sure format not right, but also total not right cause it is 22% VAT... not clear where is the mistake. Maybe the tablet did wrong?

**Comment by michelebr76** [comment]
NEW MISTAKE IN DIGITAL INVOICE.

Test has been done with new import of file (using correction of product) and on the following document
![image](https://user-images.githubusercontent.com/37332394/51444627-3cdc8f00-1cfa-11e9-8187-cf4de18e9b13.png)


Digital Invoice was generated, but in the test gave again mistakes (here the list). Mistake is again Round UP.
![image](https://user-images.githubusercontent.com/37332394/51444644-84fbb180-1cfa-11e9-9e88-8a72385f1911.png)

**Comment by michelebr76** [comment]
In addition: I ALREADY ASKED AND WROTE (see document i posted time ago) that the field "Email should be longer" in Company - Fattura Digitale

![image](https://user-images.githubusercontent.com/37332394/51444908-77e0c180-1cfe-11e9-8388-d9c48dda65dc.png)

Can you please put at least 30 digits!
