### ISSUE TITLE
CHECK - ASSEGNI. Can we manage it correctly?

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#54]
In Italy there it is common practice (especially in south) to use a special way of payment using checks (ASSEGNO/I in italian).
How it works: a person instead of giving you cash or paying you by bank transfer or credit card, gives you a check released by your bank where there are some data to be filled (basically amount and date).
In the south of Italy is commonly used it to do a post-poned payment but giving a guarantee. This is done putting a post-poned date of the check.
Legally check is similar to a cash payment (despite it involves banks)

Theoretically we can manage on Drive this payment creating a "cash account Assegni", but the question is: we can register a cash receipt with post-poned date?

**Comment by asandulsky** [comment]
we can manage everything - this is not in the system now. And we will not do at 0 cost in this project. As we have some budget later - we can plan to work on this

**Comment by michelebr76** [comment]
This is a functionalities, not an issue. 
Closed
