### ISSUE TITLE
Creating on Server space (and tablet user) to check Tablet

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#56]
I tried to open a server with Filezilla on my PC but I was not able (some problems with set up of Windows 10).
We can create in any case it on Server in Sochi where we can test the input file (after fixing the mistake).
We need to:
- have an user and password for accesing by tablet
- address where to access (it can be 1c-erp.it or others)
- to create (open for both reading and writing) three folders (usually can be under \inetpub\ftproot):
1) DNL
2) UPL
3) AGG

please provide me info about it

**Comment by asandulsky** [comment]
filezilla is FTP access-  you can not have that type of access to our server
