### ISSUE TITLE
Payment Table (both passive and active)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#57]
In Drive we already manage payments terms, but we need to have the possibility to have predefineded situation (this is a standard in Italy).

In attachment the table to be created in the system
[Payment Table.xlsx](https://github.com/asandulsky/1C-Italia/files/2686623/Payment.Table.xlsx)

In payment terms of the contract (and in documents both active and passive) we need to be able to select from this table the alternatives.

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50137503-65f9a200-02ac-11e9-8278-6c0d313fa8e9.PNG)

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50139225-1d44e780-02b2-11e9-9c74-c33194a7be08.PNG)

**Comment by michelebr76** [comment]
Done, but problem with automatic generation of lines of code MP15

![image](https://user-images.githubusercontent.com/37332394/50175589-7128ee00-02fd-11e9-9d80-cb0a0faf5c2e.png)

**Comment by michelebr76** [comment]
done. Closed
