### ISSUE TITLE
Strange situation of Gruppo Simon

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#58]
Not clear why, but basically all invoices posted by Simone gives not correct data...

check this for example:
![image](https://user-images.githubusercontent.com/37332394/50100138-02299780-0220-11e9-8375-18eb389400e2.png)

Despite it has been posted, in all reports gives 0 balance and not visible no where.

![image](https://user-images.githubusercontent.com/37332394/50100191-1c637580-0220-11e9-8195-f6314d3465aa.png)

**Comment by michelebr76** [comment]
I tried to copy and repost invoice, and it seems they works fine.... maybe mistakes can be that they were done beofre we did some changes...
or maybe an user mistake

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50140240-21263900-02b5-11e9-88e5-98876141f48a.PNG)

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50140334-74988700-02b5-11e9-8bc2-07b30cbd5ec9.PNG)

**Comment by michelebr76** [comment]
We understood that the problem can be solved SIMPLY reposting the documents.

 

M.
