### ISSUE TITLE
Payments details in Registering supplier's invoice

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#59]
This problem was initially solved (i am sure cause i checked) now not anymore available, can you please check?

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50139580-24b8c080-02b3-11e9-9a82-7dedbc7535ad.PNG)
![default](https://user-images.githubusercontent.com/38491307/50139582-25515700-02b3-11e9-9522-bd406fd60847.PNG)

**Comment by michelebr76** [comment]
![image](https://user-images.githubusercontent.com/37332394/50175433-155e6500-02fd-11e9-9c0e-1490bb3b1163.png)

done.
To be fixed the "italian" cause mistakes in text.

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50204596-7b3b0300-0376-11e9-8718-9420c1fdea1b.PNG)
