### ISSUE TITLE
Supplier INVOICE, not correctly calculating the value (after calculating invoice)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#61]
I am doing some test and to check why there is not a correct amount in SUPPLIER'S INVOICE.

Let's check all using invoice 169 dated 11.07.2018 from Portioli.

Invoice i add here (there is also in system)
[611-v51 del 11-07-2018.pdf](https://github.com/asandulsky/1C-Italia/files/2689915/611-v51.del.11-07-2018.pdf)

There are several lines and both "discount / contributo di trasporto" and the "IVA OMAGGIO".

Going at the end, there is something wrong in final calculation (please check that amount should be the same in invoice and on system)

**IMPONIBILE**: it should be the TOTAL OF AMOUNT (both of Products and of Services) 21.673,97 - the "Sconti Aggiuntivi" field (572,52)
Please note that there is an item in Service (11,01 value)

At the moment is calculated also with VAT. It is wrong, this value should be without VAT
Value we should have is:  21.101,45

In addition it is SUMMING NOT CANCELLING THE VALUE (IT should be a "-")

IVA SCONTI is not anymore working... what we should to in order it will works?

Later on there is the IVA part and better to ADD also the "OMAGGI" value

It seems correctly calculating the VALUE (omaggio, 22% and 10%), at the end it can be good if the VAT field will be the SUM of the Omaggi + 22% + 10% - THE IVA SCONTI - total should be 4.359.43

At the end we have the TOTALE FATTURA that should be 25.460,88

Now, it will be better to PUT VISIBLE THE field: Imponibile Omaggi that should be the SUM of all the AMOUT of raw with IVA OMAGGIO selected (value: 418,26)

FINAL VALUE TO PAY (DOCUMENT VALUE): 25.042,62

**Comment by michelebr76** [comment]
I opened this issue that basically is connected with what it has been already done, but not working properly.

**Comment by ValentinaKopeva** [comment]
Ok

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50212922-44241c00-038d-11e9-8e0e-2b02fb170c2f.PNG)

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50212981-6453db00-038d-11e9-9488-6ba895e42551.PNG)

I use the formulas from your example .

**Comment by ValentinaKopeva** [comment]
![default](https://user-images.githubusercontent.com/38491307/50215385-e34c1200-0393-11e9-9f83-6c6eb8b452be.PNG)

**Comment by michelebr76** [comment]
Supplier's invoice changed.
Not anymore actual. 
Issue closed
