### ISSUE TITLE
List of mistakes noticed using System of Gruppo Simon

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#62]
Here a list of mistakes noticed while using Gruppo Simon:

1) Sales INVOICE number: when you are in a Sales Invoice and you press SAVE or POST automatically the number raise of 1 unit

2) Catalog "Modalità Pagamento": is automatically creating several lines for code of Specification MP15 (I already deleted all, but after a bit it creates new one, not clear why)

3)

**Comment by ValentinaKopeva** [comment]
2.Catalog "Modalità Pagamento": is automatically creating several lines for code of Specification MP15 (I already deleted all, but after a bit it creates new one, not clear why)
This fix, 
When everyone leaves the database, you can permanently delete unnecessary elements of catalogs

**Comment by ValentinaKopeva** [comment]
1. Sales INVOICE number: when you are in a Sales Invoice and you press SAVE or POST automatically the number raise of 1 unit
______________________
In  the process of solving this issue
