### ISSUE TITLE
Supplier invoice: Sconto - error in entery - can not convert to Numeric

### ISSUE THREAD

**Issue by asandulsky** [asandulsky/1C-Italia#65]

**Comment by michelebr76** [comment]
The format of "Discount" field should be with two decimals at least (at the moment it doesn't have any decimal).
It should be like
20,50

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/53167835-2e7bde80-35ea-11e9-8e77-fe3c15e4581b.png)

**Comment by michelebr76** [comment]
ok!
Closed
