### ISSUE TITLE
Supplier invoice: OMAGGI CON RIVALSA 

### ISSUE THREAD

**Issue by asandulsky** [asandulsky/1C-Italia#67]
example in : Invoice N. 2 of Demo DB
calculates 200 euro of VAT........ 
while it should be totally different in this case the 22% 
(but could be even 10% if the item had another VAT)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/52936008-05e6b100-336c-11e9-9756-071d610066d9.png)
![image](https://user-images.githubusercontent.com/38491307/52936099-3fb7b780-336c-11e9-9a27-918fd9baaedf.png)

**Comment by michelebr76** [comment]
When we have OMAGGIO CON RIVALSA, "Amount" and "Importo with Sconto" should be zero

See picture
![omaggio](https://user-images.githubusercontent.com/37332394/52969070-5df2d700-33af-11e9-9b7e-c78d20c57510.jpg)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/53148825-f8743580-35bc-11e9-87b9-812b9b88a676.png)
Field "IMPORTO" is  obligatory. 
If this field is not filled in, then the document is not posted.

**Comment by michelebr76** [comment]
Clear.
Ok. So we should leave it.

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
fixed.
