### ISSUE TITLE
Supplier invoice: SCONTI AGGIUNTIVI in totals - should be deduct in IMPONIBILE

### ISSUE THREAD

**Issue by asandulsky** [asandulsky/1C-Italia#68]
it is added now which is wrong

SCONTI AGGIUNTIVI should deduct from IMPONIBILE

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/52934045-5eb34b00-3366-11e9-9a3d-1a2906b2b3d5.png)
SCONTI AGGIUNTIVI - is negative value.

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/52935350-3e858b00-336a-11e9-8ffa-b91a577fd725.png)

Done
Work without minus

**Comment by michelebr76** [comment]
fixed.
