### ISSUE TITLE
Supplier Invoice: IMPONIBILE should  consider Total without VAT

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#69]
The IMPONIBILE should be calculated using the TOTAL without VAT (at the moment is with VAT)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/52933910-efd5f200-3365-11e9-8773-ce30c1e8927c.png)
SCONTI AGGIUNTIVI - is negative value.

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/52935320-27469d80-336a-11e9-93f2-e7b1965f2ab5.png)
Done
Work without minus

**Comment by michelebr76** [comment]
The IMPONIBILE (in TOTALS) is wrongly calculated when we have discount.

See example in pictures:
![image](https://user-images.githubusercontent.com/37332394/52963561-6bed2b80-33a0-11e9-8fb2-611165c510f4.png)
![image](https://user-images.githubusercontent.com/37332394/52963586-7b6c7480-33a0-11e9-8d90-f9dffcb2aa52.png)

In this example the IMPONIBILE should be: 4.680 (and not: 5.709,60)

**Comment by michelebr76** [comment]
fixed.
