### ISSUE TITLE
Event: not possibile to create an incoming event (just outgoing)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#7]
Creating a new event (from CRM section), it is not possibile to choose if it is an incoming or outgoing event.
Creating it, it seems they are all considered like outgoing (you can see when you check the events list).

**Comment by michelebr76** [comment]
Any news regarding this issue?

**Comment by ValentinaKopeva** [comment]
![3333](https://user-images.githubusercontent.com/38491307/41775430-88854b6a-762c-11e8-95b7-6d3e6812b102.PNG)
Would you like to see the demarcation of the incoming - outgoing call in this list?

**Comment by michelebr76** [comment]
It is not possibile to create outgoing, just incoming 
Or the opposite. I forgot.


Eng. Michele Brustia
Tel: +7 918 4113551
Email: michele.brustia@gmail.com

**Comment by ValentinaKopeva** [comment]
Ok, we can somehow supplement this functionality or you are satisfied with everything?

**Comment by michelebr76** [comment]
The problem is: we need to be able to decide if an event is incoming or outgoing. But it is not possibile 

Eng. Michele Brustia
Tel: +7 918 4113551
Email: michele.brustia@gmail.com

**Comment by michelebr76** [comment]
About this issue (incoming and outgoing event), again I explain the problems:

it is possibile just to create INCOMING EVENT.
Not possibile to create OUTOGOING EVENT.

We need to solve it.
