### ISSUE TITLE
Digital Invoice (Sales): missing field

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#70]
The following field should be added to digital Invoice:

2.1.1.9   <ImportoTotaleDocumento>: it should be the TOTAL OF THE DOCUMENT (the total inclusind VAT)

It is in:
2   <FatturaElettronicaBody>
2.1.1   <DatiGeneraliDocumento>

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/52940784-6aa80880-3378-11e9-8cc1-583eb76ef279.png)

**Comment by michelebr76** [comment]
The opened issue is for SALES INVOICE, not supplier's invoice and refers to DIGITAL INVOICE

Not clear the comment

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/53174156-2c218080-35fa-11e9-8f47-a2bf672110d8.png)
