### ISSUE TITLE
SUPPLIER'S INVOICE: reorganizing TOTALS

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#72]
We need to reorganize the totals, deleting some fields that create confusions and that are not used in Digital Invoice.

See pictures
![totals](https://user-images.githubusercontent.com/37332394/52971510-fdb46300-33b7-11e9-926b-e14c1e10c4cc.jpg)

Fields we need to have:
- Sconti Aggiuntivi = it is a field where it is possibile to register an additional discount
- IVA sconti = it is a % of the "Sconti Aggiuntivi". As DEFAULT the VAT should be as value zero (And optionally can be changed)
- Imponibile = it is the TOTAL of the amount without VAT (to be considered both goods and services) -  "Sconti Aggiuntivi"
- Imposta = it is the TOTAL of the VAT (to be considered both goods and services) - "IVA sconti"
- Totale Fattura = Imponibile + Imposta (it is the total of the document).

The following fields should be cancelled:
- IVA OMAGGIO
- VAT 22%
- VAT 10%
- Summary Total
- Netto a pagare
- Subtotal

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/53148391-949d3d00-35bb-11e9-9657-14276f18d62b.png)

**Comment by michelebr76** [comment]
Ok. We need today to test “loading of digital Supppier invoice” and we will check if we need also other correction 

Eng. Michele Brustia
Direttore 1C Italia
Tel (IT)/WhatsApp: +39 3395821801
Tel (Ru): +7 918 4113551
Email: mb@1c-erp.it
http://1c-erp.it

**Comment by michelebr76** [comment]
Field "IVA SCONTI": as default it put 15% VAT Rate, not clear why.

Can we put as DEFAULT: IVA RATE 0%?
Later the Costumer can decide if to change.

**Comment by ValentinaKopeva** [comment]
This bug is fixed.
