### ISSUE TITLE
IMPORTING DIGITAL INVOICE - test

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#73]
The system of importing Digital Invoice should be fixed.
Test we can do on real invoice (attached in ZIP) on Gruppo Simon (if we don't have real data, we cannot test)

[IT02355260981_0HrhB.zip](https://github.com/asandulsky/1C-Italia/files/2892890/IT02355260981_0HrhB.zip)

At the moment it returns mistakes when i try it returns the following mistake:

![image](https://user-images.githubusercontent.com/37332394/53227501-a72c7a80-367e-11e9-97a2-63de1917b673.png)

**Comment by michelebr76** [comment]
Here several invoices received by Gruppo Simon (almost all they are receiveing without digital signature).
At the moment, not consider the one with Signature

[Ricevute.zip](https://github.com/asandulsky/1C-Italia/files/2903987/Ricevute.zip)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/53410278-61e8af80-39d4-11e9-819b-2e197130de8f.png)

I corrected the error, but at the moment the document is not fully filled. Working on this issue.
