### ISSUE TITLE
Digital Invoice: Header Page not working (Change link)

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#75]
The header Page is not working
![image](https://user-images.githubusercontent.com/37332394/53391053-70fc3d00-3995-11e9-962c-111646dbeef9.png)

We need simply to change the Link deleting "Sample Page")
the correct link  is: http://1c-erp.it/area-riservata/fattura-elettronica-sistema/

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54260694-b2d2d900-457a-11e9-8a8e-5ea1001f285c.png)
Fixed
