### ISSUE TITLE
SUPPLIER'S INVOICE: Ritenuta

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#76]
In the TOTALS (see pictures) we added a field called "Ritenuta Enasarco"

![image](https://user-images.githubusercontent.com/37332394/53392294-43b18e00-3999-11e9-9fac-8b2ddc361a9d.png)

we need to change it according DIGITAL INVOICE.

Requested change:
- Change field name from "Ritenuto Enasarco" to "% RITENUTA" (in Italy we have several type of it)
- Change field name from "Total Enasarco" to "Totale Ritenuta"
- Change formula for calculation of value "Totale Ritenuta": it should be the "%Ritenuta" * TotaleFattura

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54262096-6f7a6980-457e-11e9-8c79-2a36f238bf3f.png)
Fixed

**Comment by michelebr76** [comment]
Mistake in formula.
% Ritenuta is a percentage. It means we need to divide the "Totale Ritenuta" / 100

Exact formula should be: TOTALE RITENUTA = Totale Fattura * % Ritenuta / 100

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54266963-6e026e80-4589-11e9-9fc3-20149f4ab7e7.png)

check
