### ISSUE TITLE
Change standard form in Company Details - TAB Fattura Elettronica

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#77]
In company Details, TAB-> Fattura Elettronica should be changed / added some fields 

Actual SITUATION
![image](https://user-images.githubusercontent.com/37332394/54072068-00e39600-4276-11e9-9298-6561617aa1ea.png)

HOW IT SHOULD BE (I changed form, but it should be like this as standard for all)
![image](https://user-images.githubusercontent.com/37332394/54072118-85ceaf80-4276-11e9-9031-7e7f14986eb4.png)

**Comment by ValentinaKopeva** [comment]
fixed
