### ISSUE TITLE
SUPPLIER'S INVOICE -> TOTALS -> Ritenuta

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#79]
We should correctly manage RITENUTE (Witholding, we have several situations not only ENASARCO)

Here the actual situation (already changed the name that should be as default):
![image](https://user-images.githubusercontent.com/37332394/54072337-d562aa80-4279-11e9-97db-e7f509165cf1.png)

Required correction:

**ADD FIELD "Tipo di Ritenuta"**
We should be able to choose from two options:
a) RT01 - Ritenuta persone fisiche
b) RT02 - Ritenuta persone giuridiche

**ADD FIELD "Causale del pagamento"**
The list of all possibile options is in this excel file
[Causale Pagamento Ritenuta.xlsx](https://github.com/asandulsky/1C-Italia/files/2948438/Causale.Pagamento.Ritenuta.xlsx)

MISTAKE IN CALCULATION FORMULA:
The field "Importo al Netto della Ritenuta" should be calculated as follow: TOTALE FATTURA - IMPORTO RITENUTA

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54433903-0b060880-473e-11e9-8000-dbd0036f80d1.png)
Importo al Netto della Ritenuta = TOTALE FATTURA *IMPORTO RITENUTA/100
Why is  formula  wrong?

**Comment by michelebr76** [comment]
Total should be: 27,8080

 

Now it is 2.780,80 (100 times more)
