### ISSUE TITLE
Sales Planning - Impossible to create

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#8]
It is not possibile to create Sales Planning.
The problem is: not possibile to select the "planning date" (it seems a variable is missing).

**Comment by michelebr76** [comment]
Any news regarding this issue?

**Comment by ValentinaKopeva** [comment]
Error fixed
![4](https://user-images.githubusercontent.com/38491307/41774472-91bda780-7628-11e8-805e-8588e255ccca.PNG)

**Comment by michelebr76** [comment]
Ok! I will check a bit later

Eng. Michele Brustia
Tel: +7 918 4113551
Email: michele.brustia@gmail.com

**Comment by michelebr76** [comment]
I think can be ok

Eng. Michele Brustia
Tel: +7 918 4113551
Email: michele.brustia@gmail.com
