### ISSUE TITLE
Add a column in "Modalità di pagamento" List

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#80]
At the moment the "Modalità di pagamento is as follow:

![image](https://user-images.githubusercontent.com/37332394/54072586-02fd2300-427d-11e9-9845-d7a7d21550e9.png)

it is not for the user to understand which one to choose cause there is not the description field (JUST the abbreviation for digital invoice) Should be added the column with long description

The table should be like this
[ModalitàDiPagamento.xlsx](https://github.com/asandulsky/1C-Italia/files/2948452/ModalitaDiPagamento.xlsx)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54263556-22989200-4582-11e9-83da-18800920d95c.png)
fix
