### ISSUE TITLE
SUPPLIER'S INVOICE -> TOTALS -> ADD POSSIBILITY TO MANAGE DISCOUNT AND MARKUP

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#81]
In Supplier's Invoice, we need to allow the possibility to manage not only Discount (like now) but also Markup (according digital invoice field).

Actual situation (NOTE: already changed fields and should be as default like this)
![image](https://user-images.githubusercontent.com/37332394/54072734-2a54ef80-427f-11e9-9447-c046d5de8383.png)

Changes to be done un first part (Sconti/Maggiorazioni)

**1) Add field "Tipo"**
There should be two options possible:
a) "SC" (Default)
b) "MG"

Changes in formulas in calculation of totals:
In case of "SC" (THIS IS THE ACTUAL SITUATION)
- Calculating "Imponibile" the field "Valore" should be deducted "-" to the others
- Calculating "Imposta" the field "IVA SCONTI" should be deducted "-" to the others

In case of "MG": (OPTION NOT MANAGED AT THE MOMENT)
- Calculating "Imponibile" the field "Valore" should be added"+" to the others
- Calculating "Imposta" the field "IVA SCONTI" should be added "+" to the others

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54749306-2dd46900-4be5-11e9-8268-c95998e600d5.png)
![image](https://user-images.githubusercontent.com/38491307/54749254-0c737d00-4be5-11e9-9035-3810c85a96f0.png)
![image](https://user-images.githubusercontent.com/38491307/54749278-1ac19900-4be5-11e9-94f9-78d6162f2592.png)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54749674-60cb2c80-4be6-11e9-82ae-a53e14b809d5.png)
![image](https://user-images.githubusercontent.com/38491307/54749711-7fc9be80-4be6-11e9-962e-0b4721df3f72.png)
