### ISSUE TITLE
List "MODALITA DI PAGAMENTO" - Invert Header "Description" and "Code of Specification" 

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#85]
We need to invert the header of the list.
Description should refer to "Contanti", "Assegno" etc.......
While "Code of Specification" to MP01, MP02, etc...

![image](https://user-images.githubusercontent.com/37332394/54264601-c3cc1c00-4573-11e9-9c06-74a976ab38be.png)

Please note:
The code (MP01, MP02, etc...) are the one linked to Digital Invoice (during change don't ruin this).

In addition, in selection field, the user should view the "description"

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54269740-f9cac980-458e-11e9-900c-7d960eedd935.png)
