### ISSUE TITLE
Not registering Bank Payment to Suppliers

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#86]
I am trying to do do bank payment of a Suppliers invoice but something wrong.

Reference document: Supplier Invoice N. 3 of 03/01/2019

I do Bank Payment and it allows me to do it, but it is not registering anything and allowing also to do multiple payment on the same document.
Looking at documents you can fine several of them (see photo)

![image](https://user-images.githubusercontent.com/37332394/54267325-4c998680-4579-11e9-9eed-55bebf1ce8cd.png)

but even in report they are not visible:

![image](https://user-images.githubusercontent.com/37332394/54267419-794d9e00-4579-11e9-88e0-135e86d9f240.png)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54422799-4c87bb00-4720-11e9-968c-0620b7cd421f.png)
![image](https://user-images.githubusercontent.com/38491307/54422843-645f3f00-4720-11e9-9448-09c12ff382dc.png)

**Comment by michelebr76** [comment]
can you tell me which one was the mistake?
- user mistake or it has been fixed?

**Comment by ValentinaKopeva** [comment]
This is user mistake. 
Documents were linked incorrectly.

**Comment by michelebr76** [comment]
Ok.

But how did you do payment? 

 

From documents or from Cash Management?

**Comment by ValentinaKopeva** [comment]
from document
