### ISSUE TITLE
Payment Terms - Problems with CASH Payments

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#87]
If we select "CASH" payment in Payment terms, we cannot specify the "CASH" account but just "Bank Account" (this is not correct cause Cash Payments should refers just to Cash Account)

See pictures.
![image](https://user-images.githubusercontent.com/37332394/54274799-5925db00-4589-11e9-96e2-b2aed5faefee.png)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54424211-768eac80-4723-11e9-9306-fca501aba909.png)

The system requires one payment date.

**Comment by michelebr76** [comment]
ok. but works a bit strange.
