### ISSUE TITLE
CASH PAYMENT in supplier's invoice

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#88]
Mistake when we choose CASH payment in supplier's invoice.
Problem is the same that we had in SALES INVOICE (and that it was solved)

in addition there are two "DUE DATE" field and the first (the one on left) not working

![image](https://user-images.githubusercontent.com/37332394/54428081-a8504500-471c-11e9-83b4-f2416dd5548b.png)

**Comment by ValentinaKopeva** [comment]
![image](https://user-images.githubusercontent.com/38491307/54431260-feca7d00-4736-11e9-8ed2-baedf9185af7.png)

**Comment by michelebr76** [comment]
it should be still fixed:
- when i select "Cash" i need to have CAsh Account
- When i select single, there should not be table


![image](https://user-images.githubusercontent.com/37332394/54437247-7e0a8180-4734-11e9-812b-a79ac43c5616.png)
