### ISSUE TITLE
Gruppo Simon - Not possible to start "Digital Invoice"

### ISSUE THREAD

**Issue by michelebr76** [asandulsky/1C-Italia#99]
In gruppo Simon there is not digital invoice link.

When i go in section SALES, and i select "Additional Processors", digital invoice is not in the list.

I try to Configure lists and it apperars (see picture)

![image](https://user-images.githubusercontent.com/37332394/56658472-f866e380-669a-11e9-9173-5c2611555e39.png)

but when i select it, it doesn't allow me to add in the list and i am blocked.

**Comment by ValentinaKopeva** [comment]
Check this)
